PATCHES = {
    # ---------- 31-1
    ("31-1", 1): {"opts": ["They were stretched across the whole valley floor.", "They were fixed tightly in a narrow space.", "They were hidden from view.", "They were scattered over a wide, open plain."]},
    ("31-1", 8): {"q": "What does paragraph 2 show you about Agnes’s character? Give one quality and support it with evidence from the paragraph. (1 mark for the quality, 1 mark for the evidence.)",
                  "g": "1 mark for a suitable quality (determined, stubborn, confident, brave, capable). 1 mark for evidence from the paragraph. Max 2."},
    ("31-1", 10): {"opts": ["She disliked working with other people on new ideas.", "She was jealous of other people’s clever ideas.", "She refused to accept any help from others.", "She organised everyone and got things done."]},
    ("31-1", 13): {"opts": ["A young woman gets lost in the mountains one winter and is rescued by neighbours.", "A shopkeeper trains a girl to remember the prices of everything in the shop.", "A shepherd’s daughter loses her flock in the snow and has to search for it.", "A determined postwoman serves her valley and finds new ways to help."]},
    # ---------- 31-2
    ("31-2", 1): {"opts": ["A large wildflower meadow", "A community orchard", "Rows of vegetable beds", "A small native wood"]},
    ("31-2", 2): {"opts": ["Dislike very much", "Forget about entirely", "Expect it in advance", "Deliberately ignore"]},
    ("31-2", 9): {"opts": ["To suggest that the council should close it down", "To say that the High Street is an unpleasant place to park", "To complain about the high price of parking there", "To suggest the parking problem is not that serious"]},
    ("31-2", 12): {"m": 1,
                   "q": "In the paragraph beginning “There is a further difference”, the writer compares a car park with an orchard. What difference does she want the councillor to notice? Explain in your own words.",
                   "a": "A car park is permanent and cannot be undone, while an orchard gets better as time goes on.",
                   "g": "1 mark for the contrast: a car park is permanent / cannot be undone, whereas an orchard grows more valuable over time. Accept a clear statement of one side if the contrast is implied."},
    ("31-2", 13): {"opts": ["The council must not build any car parks anywhere in Willowbrook.", "The town needs many more volunteers to help with local projects.", "A community orchard would help the town more than a car park.", "Fruit trees are easy to look after and need very little care."]},
    # ---------- 31-3
    ("31-3", 1): {"opts": ["Bounces off sharply", "Burns fiercely downwards", "Slips through softly", "Stays still"]},
    ("31-3", 6): {"g": "1 mark for the idea of glowing or warm golden light. 1 mark for feeling surrounded, enclosed or cosy. Max 2."},
    ("31-3", 9): {"opts": ["Most of the trees are hidden in the thick autumn fog.", "Important changes happen below ground, unseen.", "The wood is busy with visitors on autumn weekends.", "The squirrels work in secret among the branches."]},
    ("31-3", 12): {"opts": ["A squirrel and a wood pigeon frighten a visitor from the path.", "Beech nuts on the path are dangerous to walk on.", "Animals and seeds are getting ready for the coming season.", "The wood is completely silent and nothing moves."]},
    # ---------- 31-4
    ("31-4", 1): {"opts": ["As wide as a thick pencil", "As wide as an adult’s little finger", "Thicker than a strong washing line", "A little wider than a human hair"]},
    ("31-4", 2): {"opts": ["To an extreme degree", "Only to a small degree", "Once in a long while", "In a rough way"]},
    ("31-4", 7): {"m": 1, "q": "Why does light stay inside the core of a fibre? Use the text to help you.",
                  "a": "The glass in the core is different from the cladding, so when light meets the boundary it bounces back into the core (total internal reflection).",
                  "g": "1 mark for the idea that light bounces / reflects back into the core when it meets the boundary with the cladding (accept “because the core and cladding are different glasses so the light is bounced back”). Do not accept “because it is trapped” with no reason."},
    ("31-4", 10): {"opts": ["They are much cheaper to repair than copper cables when they break.", "They are made of lightweight plastic that is safe to handle and cheap.", "They carry more information and ignore electrical interference.", "They do not need a detector at the receiving end of the cable."]},
    # ---------- 31-5
    ("31-5", 1): {"opts": ["That crows were the very best of all birds at it", "That only humans and their close relatives could do it", "That it could only be done by birds living on remote islands", "That it was far too dangerous for most animals to try"]},
    ("31-5", 2): {"opts": ["Rushed and rather careless", "Gentle and rather slow", "Very careful and exact", "Unwilling and reluctant"]},
    ("31-5", 9): {"opts": ["It proved the crow had met a new problem and solved it.", "It meant the crow could not have been very hungry at the time.", "It showed that crows dislike the feel and smell of metal.", "It meant the experiment could not be repeated by other scientists."]},
    ("31-5", 12): {"opts": ["Crows are the cleverest animals in the world, cleverer than any bird or ape.", "Grubs are hard to find in rotting wood, so crows must use special tools.", "Scientists cannot explain anything about how crows behave or think.", "Crows make and use tools, which changes what we believed birds could do."]},
    # ---------- 31-6
    ("31-6", 1): {"opts": ["Copy it out very neatly", "Throw it away quickly", "Work out with some effort", "Read it out loud to others"]},
    ("31-6", 8): {"opts": ["She wanted the coat to be sold cheaply to the first person in the shop.", "She wanted to hide the key from the customers who might steal it.", "She was angry that nobody had bought the coat after so many months.", "She hoped someone curious, whom others overlooked, would find the key."]},
    ("31-6", 11): {"g": "1 mark for the piano waiting or being lonely. 1 mark for Ines being the right person or it being meant to be. Max 2."},
    ("31-6", 12): {"opts": ["A girl buys a second-hand coat and finds treasure hidden in its lining.", "A girl follows a hidden note to a teacher who wants her piano played.", "A girl gets lost on her way to buy trainers and has to ask a stranger.", "A shop assistant tricks a girl into paying too much for an old coat."]},
    # ---------- 32-1
    ("32-1", 1): {"opts": ["Straight and very smooth", "Twisted and rough with age", "Covered in pale blossom all over", "New and freshly grown"]},
    ("32-1", 3): {"m": 1,
                  "a": "He felt sad or embarrassed about no longer being able to look after the allotment himself, because asking seemed to cost him something.",
                  "g": "1 mark for a sensible feeling (sad, reluctant, embarrassed, proud, missing it) linked to no longer managing the allotment / his knees / “the request had cost him a good deal”."},
    ("32-1", 8): {"m": 1, "q": "Why did the narrator decide to give the pears away rather than sell them? Use paragraph 5 to help you.",
                  "a": "The narrator wanted to share them with neighbours who had been kind or were too busy to get fruit (for example Mr Okafor, who had left chutney).",
                  "g": "1 mark for the idea of kindness / sharing / repaying kindness. Accept a reference to Mr Okafor’s chutney or to the busy couple with twins as the reason."},
    ("32-1", 9): {"opts": ["Unbounded excitement", "Total confusion", "Sheer weariness", "Deep seriousness"]},
    ("32-1", 11): {"m": 1,
                   "a": "The pear meant a great deal to him: it reminded him of the allotment he missed, as a letter from someone dear would.",
                   "g": "1 mark for the idea that the pear was precious / welcome / a reminder of something or someone he missed."},
    ("32-1", 12): {"opts": ["He wants the small pears kept back to eat himself.", "He thinks the narrator has wasted some fruit by picking it.", "He is checking the narrator took his advice.", "He cannot see from his chair how many are left."]},
    ("32-1", 13): {"opts": ["Old trees that are well cared for produce the best fruit.", "Some people are simply better at gardening than others.", "Families should never move away from their old house.", "Patience and sharing matter more than the fruit itself."]},
    # ---------- 32-2
    ("32-2", 1): {"opts": ["The water is far too warm for them.", "There is little air in the soil.", "Animals eat all of the plants first.", "The plants are too tough to break down."]},
    ("32-2", 3): {"opts": ["Bitterly cold all over", "Dark and quite crumbly", "Soaked right through", "Newly planted again"]},
    ("32-2", 6): {"m": 1,
                  "a": "Peat locks in huge amounts of carbon, because plants do not rot there.",
                  "g": "1 mark for the idea that a large amount of carbon is stored / kept locked in the peat. A supporting detail (plants do not rot; more carbon than all the forests) may be given but is not required."},
    ("32-2", 10): {"g": "1 mark for each of two sensible effects. Accept: “sticky” shows the hairs trap insects; “glistening” makes the reader picture the hairs as wet and shiny, or as tempting to insects. Max 2."},
    ("32-2", 13): {"opts": ["To explain how peat is dug up and used in gardens", "To show restoring bogs is slow but worthwhile", "To warn readers that bogs are already beyond saving", "To persuade readers to visit a bog this summer"]},
    ("32-2", 14): {"opts": ["Bogs are wet places where many rare plants and insects live.", "Peatlands store carbon, so protecting them matters.", "Gardeners should never use any kind of compost at home.", "Rainforests are much less important than bogs are."]},
    # ---------- 32-3
    ("32-3", 1): {"opts": ["It was hidden from everyone’s view.", "It was wide open and obvious.", "It was tiny and hard to see clearly.", "It was full of dust and fluff."]},
    ("32-3", 9): {"opts": ["They were very cold and stiff.", "They were moving quickly and easily.", "They seemed unwilling to come apart.", "They were shaking with fear and worry."]},
    ("32-3", 10): {"m": 1, "q": "Why did Callum take the queen to the art room instead of telling Mr Adeyemi?",
                   "a": "He was embarrassed / afraid of being blamed, so he tried to mend it himself.",
                   "g": "1 mark for a sensible reason: embarrassed, afraid of getting into trouble, or wanted to fix his own mistake quietly."},
    ("32-3", 11): {"m": 1, "q": "“Callum’s face flushed the colour of beetroot.” What does this description tell the reader about how Callum felt?",
                   "a": "He was embarrassed (caught out); his face went deep red.",
                   "g": "1 mark for embarrassed / ashamed / caught out / uncomfortable. Do not accept “angry” or “hot” alone."},
    ("32-3", 12): {"opts": ["He wants the children to learn to make their own glue.", "Friends should always share their art supplies fairly.", "The queen will need to be replaced by a new one.", "A mistake that has been put right can be forgiven."]},
    ("32-3", 13): {"opts": ["A pupil secretly steals a chess piece in order to win the big game.", "A careful observer solves a puzzle and helps a nervous friend.", "A teacher loses a chess piece and blames all of the children.", "A club cancels its tournament because of a broken piece."]},
    # ---------- 32-4
    ("32-4", 1): {"opts": ["Museums are very cheap to run and look after.", "The objects belong, in a sense, to everybody.", "Families prefer visiting on wet afternoons.", "Tickets are always far too expensive for families."]},
    ("32-4", 9): {"m": 1, "q": "The writer says taxpayers who never visit a museum “still help to fund a free one”. What point are the supporters of charging making?",
                  "a": "People who never visit still pay for the museum through taxes, so it is fairer for the people who use it to pay.",
                  "g": "1 mark for the idea that non-visitors pay through taxes / that this is unfair / that people who use the museum should pay."},
    ("32-4", 11): {"opts": ["Museums should always be free of charge for every single visitor.", "Museums should always charge every visitor a fair entry fee.", "Both sides make fair points and communities should decide.", "Museums are no longer as important to people as they were."]},
    ("32-4", 13): {"opts": ["Charging can be fair, and compromises have been found.", "Taxpayers dislike museums and want to stop paying for them.", "Special exhibitions are always far too expensive for families.", "People should pay nothing at all to enter museums."]},
    # ---------- 32-5
    ("32-5", 6): {"m": 1, "q": "The first sheet was so thin in one corner that daylight shone through “like a window”. What does this comparison show about the paper?",
                  "a": "It was very thin and see-through, like clear glass.",
                  "g": "1 mark for very thin / see-through / you could see light through it."},
    ("32-5", 9): {"m": 1,
                  "a": "So that Haru would remember how it feels to be a beginner / to be bad at something.",
                  "g": "1 mark for the idea of remembering how it feels to be bad at something or to be a beginner. Accept “to remind her of what learning is like”."},
    ("32-5", 11): {"opts": ["It was warm and gentle on her hands.", "It slowly wore away at her fingers.", "It was no longer troubling her.", "It came and went in sudden bursts."]},
    ("32-5", 13): {"opts": ["Working in cold water is the best way to become skilled.", "Apprentices should never ask their masters too many questions.", "Learning takes time and mistakes are worth remembering.", "Old ways of doing things are always better than new ones."]},
    # ---------- 32-6
    ("32-6", 2): {"opts": ["Quick and needing hardly any effort", "Slow and needing a lot of effort", "Beautiful and pleasing to look at", "Dangerous and risky to do"]},
    ("32-6", 13): {"opts": ["Gutenberg’s metal letters made books quicker and cheaper, and printing spread widely.", "Scribes were more skilful than printers, although printers worked much faster than they did.", "Gutenberg became very rich from selling his famous Bible to churches across Europe.", "Printing began in England in 1476 and soon spread to all of the towns there."]},
    # ---------- 31-7
    ("31-7", 7): {"m": 1, "q": "Look at paragraph 2. The author says “Many people might have given up at that point”. What does this show about Elizabeth?",
                  "a": "That she was determined and did not give up, even when it was discouraging.",
                  "g": "1 mark for determined / persistent / brave / did not give up. Do not accept answers that only say she was turned away."},
    ("31-7", 14): {"g": "1 mark for a sensible prediction (more women doctors / more women in medicine). 1 mark for a reason from paragraph 5. Max 2."},
    # ---------- 32-7
    ("32-7", 8): {"m": 1,
                  "a": "She thought old books might already hold useful clues, so reading them would show which plants were worth testing.",
                  "g": "1 mark for a sensible reason: old knowledge / recipes might contain clues, or it would save testing everything."},
    ("32-7", 14): {"m": 1, "q": "The last sentence says that Tu’s discovery “shows how old knowledge and careful modern testing can work side by side”. Explain what this means.",
                   "a": "Old books and recipes gave Tu useful clues, and modern testing showed which plant and method really worked, so each helped the other.",
                   "g": "1 mark for the idea that old knowledge and modern testing were used together and helped each other. An example (Ge Hong’s text and its clue not to heat the plant, plus testing extracts) may be given but is not required."},
    # ---------- 32-8
    ("32-8", 5): {"m": 1,
                  "a": "Black holes give off radiation and so lose energy, meaning that over a very long time one could disappear.",
                  "g": "1 mark for the idea that black holes give off radiation / lose energy, so they can slowly shrink and fade away."},
}
