PATCHES = {
    ("25-1", 2): {"opts": ["Held it tightly with both hands", "Handled it clumsily, almost dropping it", "Threw it away on purpose", "Polished it slowly with a clean, soft cloth"]},
    ("25-1", 13): {"opts": ["A runner wins a gold medal for his team without any help at all.", "A nervous runner overcomes his fear and helps his team.", "A coach decides to change the order of the team before a big race.", "A runner from Hillcrest wins the race after a very fast start."]},
    ("25-2", 1): {"opts": ["In the stomach, just below the ribs", "In the chest, slightly to the left", "In the neck, just below the head", "In the right side of the chest, near the lung"]},
    ("25-2", 13): {"opts": ["The heart pumps blood around the body and can be kept healthy.", "Only athletes have strong hearts, because they train their bodies every day.", "Blood is made in the ribs and carried to the heart by doctors.", "Doctors use stethoscopes to build hearts that are too weak or small."]},
    ("25-3", 1): {"opts": ["Children must work in factories from the age of five.", "School must be free for every child in the country.", "Children aged five to ten must go to school.", "Teachers must use paper instead of slates."]},
    ("25-3", 3): {"opts": ["Looked at very closely", "Called out in a loud voice", "Taught in a different way", "Ignored on purpose"]},
    ("25-3", 13): {"opts": ["Victorian children never went to school, so they stayed at home.", "Victorian schools followed strict routines and taught basic skills.", "Victorian teachers had a lot of computers to help every class.", "Victorian schools were closed in the afternoon so children could play."]},
    ("25-4", 3): {"opts": ["Nervous and frightened", "Bright and cheerful", "Sleepy and slow", "Showing no respect"]},
    ("25-4", 11): {"opts": ["The sunrise fills the sky and houses with colour.", "A storm is coming in from the sea towards the bay.", "The houses are being painted by the villagers.", "The narrator gets lost on the hill above the village."]},
    ("25-4", 12): {"opts": ["Worried and anxious", "Bored and fed up", "Calm and contented", "Angry and furious"]},
    ("25-5", 2): {"opts": ["Easy to forget after a short time", "Very loud and hard to ignore", "Easy to remember for a long time", "Very difficult to do without help"]},
    ("25-5", 10): {"g": "1 mark for each of two correct reasons. Accept any two of: seeds are cheap; tools can be donated / given; a garden can be very small (containers or raised beds). Max 2."},
    ("25-5", 13): {"opts": ["Gardens cost far too much money for most schools to afford.", "A school garden has many benefits, so schools should have one.", "Children should only ever learn outdoors, never in a classroom.", "Bees are more important than the pupils who visit the garden."]},
    ("25-6", 3): {"opts": ["Hanging loosely down", "Tearing into small pieces", "Being tied up tightly", "Blowing far away in the wind"]},
    ("25-6", 7): {"g": "1 mark for each. Accept any two of: stayed calm / reassured them; carried them to the car; put them in the car out of the wind and rain. Max 2."},
    ("25-6", 11): {"opts": ["He thought the broken pole looked very funny", "He was cross that Zainab had touched the pole", "He was amazed and pleased with Zainab’s idea", "He wanted to go home and leave the tent behind"]},
    ("25-6", 12): {"opts": ["A family goes home early because a storm ruins the trip.", "A girl is so frightened of camping that she stays at home.", "Dad and Idris build a tent by a stream in the hills.", "A camping trip is saved when a girl mends a tent pole."]},
    ("26-1", 1): {"opts": ["Ten minutes", "Twenty minutes", "Thirty-five minutes", "Forty-five minutes"]},
    ("26-1", 3): {"opts": ["Grew bigger and bigger every minute", "Disappeared from view completely", "Moved slowly closer to them", "Became darker and darker"]},
    ("26-1", 11): {"opts": ["Elsie is angry with Ravi for getting them lost.", "Elsie uses the compass to help find the way.", "Ravi has forgotten the way to the jetty.", "The cousins decide to go back to the shore."]},
    ("26-2", 3): {"opts": ["Always wanting more than you need", "Feeling very tired all the time", "Being unkind to animals and people", "Working very hard all day long"]},
    ("26-2", 9): {"g": "1 mark for each clue. Accept any two of: he crept into the cottage at night; he carried off / stole the mill; he wanted the mill only for himself; he planned to sell salt for a fortune. Max 2."},
    ("26-3", 1): {"opts": ["On the evening of Po Po’s birthday", "On the last evening before New Year", "On the first warm day of summer", "At the very end of each week in the year"]},
    ("26-3", 3): {"opts": ["She was frightened of everyone in the kitchen", "She was in charge and everyone obeyed her", "She was tired and wanted a rest from cooking", "She did not know how to cook very well"]},
    ("26-3", 9): {"g": "1 mark for each point. Accept: her pleats stayed in place; she became calmer, happier or more relaxed (humming); she felt more confident. Max 2."},
    ("26-3", 12): {"opts": ["A girl learns to be patient and her first dumpling brings luck.", "A boy teases his cousin about her cooking at the family dinner.", "A family moves to a new flat just before the New Year begins.", "A grandmother loses her silver coin and everyone searches for it."]},
    ("26-4", 1): {"opts": ["The hot, dry deserts in the north of Africa", "The rainforests of Borneo and Sumatra in Asia", "The high, snowy mountains of South America", "The wide, flat grasslands of eastern Australia"]},
    ("26-4", 4): {"opts": ["Very large and very heavy", "Living high up in the trees", "At great risk of disappearing", "Kept safe in zoos all their lives"]},
    ("26-4", 7): {"opts": ["Nests, babies and learning", "Fruit that orangutans like to eat", "Dangers in the forest", "How people can save the rainforest"]},
    ("26-5", 2): {"opts": ["Water freezing into solid ice at night", "Water turning into a gas or vapour", "Water flowing along into a river", "Water falling down from a cloud"]},
    ("26-5", 10): {"opts": ["Plants do not need rain to grow well.", "Rain flows or soaks in and it starts again.", "Rivers always dry up completely in the summer.", "Soil is made from rain and dust."]},
    ("26-5", 13): {"opts": ["Water moves in a never-ending cycle that gives us rain.", "Rain is a nuisance because it spoils picnics and plans for the day.", "The Sun is a very large star that heats the whole of the Earth.", "Snow and hail are exactly the same thing in different weather."]},
    ("26-6", 3): {"opts": ["Sad that it was not as good as hoped", "Very tired after a long, busy day at school", "Extremely angry with someone else", "Worried about being late for the lesson at school"]},
    ("26-6", 10): {"opts": ["A soldier’s invention gave Louis an idea", "Louis learns to play the organ at church", "How a school library works for its readers", "A special lamp for reading books at night"]},
    ("25-7", 6): {"g": "1 mark for each rule from paragraph 2. Accept any two of: each sailor sails alone; without stopping; without any help. Max 2."},
    ("25-7", 8): {"opts": ["Easy to do and quick to finish for anyone", "Hard and needing great courage", "Cheap for most sailors to try", "Silly and far too dangerous"]},
}
