PATCHES = {
    ("27-1", 1): {"opts": ["In a stone hut on the ridge", "In a café down in the valley", "In a car at the bottom of the hill", "At a picnic table beside the path"]},
    ("27-1", 3): {"opts": ["Quickly and without stopping", "Noisily and clumsily", "Slowly and carefully", "Without any care at all"]},
    ("27-1", 10): {"g": "1 mark for each way. Accept any two of: told them to stay close / stood still and thought / reminded them about the blue dots / had them hold hands and search in a line. Max 2."},
    ("27-1", 12): {"opts": ["A family gets lost in the fog and never reaches the top.", "A family follows a trail through fog to reach a hut.", "A boy discovers a hut in the mountains.", "A ranger rescues a family from bad weather on the hill."]},
    ("27-2", 3): {"opts": ["As a result of this", "In spite of that", "At the same time as that", "After all of that"]},
    ("27-2", 10): {"g": "1 mark for each. Accept any two of: children counted tadpoles on the way to school / Mr Chen sat beside it every afternoon / it was the most popular spot on the lane. Max 2."},
    ("27-2", 12): {"opts": ["A builder digs a pond in a garden with a very large digger.", "Neighbours build a pond and Jaswinder changes his mind.", "Frogs and hedgehogs move into a garden after some rain.", "A boy fills a notebook with facts about wildlife in the garden."]},
    ("27-3", 2): {"opts": ["It was rusty and falling apart", "It was shiny and cared for", "It was brand new and never used", "It was very heavy to lift"]},
    ("27-3", 10): {"g": "1 mark for each detail. Accept any two of: she stopped / the attic went silent / she gave a small, astonished laugh / she took it tenderly, like a butterfly / she said she had forgotten how much she loved the stage. Max 2."},
    ("27-3", 12): {"opts": ["A child finds a photograph and learns about Nana.", "A child is frightened of a rocking horse in the attic.", "A grandmother spends the day clearing out her attic.", "A child loses a torch in the dark attic and has to look for it."]},
    ("27-4", 1): {"opts": ["Six", "Ten", "Twelve", "Fifteen"]},
    ("27-4", 2): {"opts": ["All sharing exactly the same view", "Split by different opinions", "Quiet, calm and peaceful", "Joined firmly together"]},
    ("27-4", 12): {"g": "1 mark for each problem. Accept any two of: they spoil the view / they might make noise / they could harm birds / they only make electricity when it is windy. Max 2."},
    ("27-4", 13): {"opts": ["To persuade readers that the company’s plan is the right one", "To set out both sides so readers can decide for themselves", "To explain how a wind turbine works", "To tell a story about a village and its wind farm"]},
    ("27-5", 1): {"opts": ["A school for scientists in Scotland", "St Mary’s Hospital in London", "A factory in the city of Oxford", "A farm in the countryside"]},
    ("27-5", 3): {"opts": ["Make it much stronger than before", "Remove the other things from it", "Make it colder by chilling it", "Make it cheaper to buy"]},
    ("27-5", 11): {"opts": ["Oxford scientists made penicillin in larger amounts.", "Fleming stopped his research and retired from the hospital.", "Doctors stopped using penicillin as it did not work.", "A factory closed down after a fire."]},
    ("27-5", 12): {"g": "1 mark for each reason. Accept any two of: bacteria cause many illnesses / penicillin could treat serious infections / it has helped millions of people / it began the antibiotics. Max 2."},
    ("27-5", 13): {"opts": ["Small details can lead to great discoveries.", "Scientists should go on holiday more often than they do.", "Mould is always dangerous to people.", "Bacteria are easy to grow in a laboratory."]},
    ("27-6", 1): {"opts": ["Golden yellow", "Deep black", "Bright orange", "Bright red"]},
    ("27-6", 3): {"opts": ["Boldly standing up to danger", "Very shy and easily scared", "Rather sleepy and slow to move", "Easy to please and friendly"]},
    ("27-6", 11): {"q": "Give two things Arctic terns do to protect their eggs and chicks.",
                   "a": "Both parents take turns keeping the eggs warm; they swoop down and peck intruders; the parents bring the chicks small fish.",
                   "g": "1 mark for each thing. Accept any two of: both parents take turns keeping the eggs warm / swoop down and peck intruders (on the head) / bring the chicks small fish. Max 2."},
    ("27-6", 12): {"opts": ["How terns choose their route", "How terns make their nests in spring", "Why terns are afraid of big ships", "The kinds of food that terns like"]},
    ("27-6", 13): {"opts": ["A small bird makes an amazing journey every year.", "Terns are the biggest of all the seabirds in the world.", "Terns never stop to rest during the whole year.", "Fish are harder to find in the north in autumn."]},
    ("28-1", 7): {"opts": ["Proud of how well she was doing", "Angry with Mr Adeyemi", "Bored with her new job", "Worried that she was failing"]},
    ("28-1", 9): {"g": "1 mark for each clue. Accept any two of: trembling / huddled in a corner / small / nibbled the bread. Max 2."},
    ("28-1", 11): {"opts": ["Kindness can matter more than following every rule.", "Lanterns are difficult to light in the rain and wind.", "It is best to keep secrets from other people.", "Apprentices should never ask questions."]},
    ("28-2", 2): {"opts": ["Without any cost at all", "With nothing holding it back", "Without making any noise at all", "Without anyone seeing it"]},
    ("28-2", 8): {"opts": ["How Earth is like a giant magnet", "Why the metals inside Earth are hot", "Where the North Pole is found on Earth", "How magnets are made in factories"]},
    ("28-2", 9): {"opts": ["Very hot", "Well hidden", "Very slow", "Very large"]},
    ("28-2", 12): {"g": "1 mark for each. Accept any two of: another magnet / a strong magnet / a large piece of iron / a big lump of iron or heavy metal. Max 2."},
    ("28-3", 11): {"g": "1 mark for each. Accept any two of: played every Sunday afternoon at the kitchen table / used buttons for missing pawns / Grandad never let Marcus win. Max 2."},
    ("28-3", 12): {"opts": ["Marcus chooses Grandad’s birthday over a chess final.", "Marcus wins the county chess final and celebrates with his team.", "Marcus is angry with his teacher for being unfair.", "Grandad forgets his own birthday until the evening."]},
    ("28-4", 1): {"opts": ["Rivers that flow through Mexico City", "Ponds in a forest in Mexico", "Lakes and canals near Mexico City", "The sea near the coast of Mexico"]},
    ("28-4", 4): {"opts": ["Very cold and icy", "Deep, quiet and calm", "Cloudy and dark", "Full of tiny fish"]},
    ("28-4", 11): {"g": "1 mark for each. Accept any two of: leg, tail (part of), heart (parts of). Max 2."},
    ("28-4", 13): {"opts": ["How to keep an axolotl as a pet", "Why axolotls are in danger", "The colours of axolotls", "How lakes are formed"]},
    ("28-5", 9): {"g": "1 mark for each. Accept any two pieces of evidence of wonder or admiration (held her breath, small sun, surgeon comparison, could hardly sleep, watching closely). Do not accept the name “glory hole” making her smile, which shows amusement, not admiration. Max 2."},
    ("28-5", 12): {"opts": ["Uncle Femi gets tired and stops work for the day.", "Uncle Femi shapes the glass into a bird.", "Amara asks Uncle Femi how glass is made.", "The bird falls off the bench and breaks on the floor."]},
    ("28-6", 4): {"opts": ["Slightly frightened", "Very interested", "Rather tired", "Quite confused"]},
    ("28-6", 10): {"g": "1 mark for each reason. Accept any two of: strong, steady winds / soft sand to land on / far from any town so they were not disturbed. Max 2."},
    ("28-6", 12): {"opts": ["Two bicycle sellers were given a large museum to run.", "Two brothers built a flying machine and flew it.", "Strong winds are dangerous for flying machines.", "A wooden machine was built and then thrown away unused."]},
    ("27-7", 2): {"g": "1 mark for each. Accept any two of: she was a healer / used herbs and remedies / helped people who were unwell / she ran a boarding house (or small hotel). Max 2."},
    ("28-7", 1): {"opts": ["Enterprise", "Atlantis", "Endeavour", "Columbia"]},
    ("28-7", 4): {"g": "1 mark for each. Accept any two of: she read library books / she visited museums / similar (e.g. reading about science, going to museums). Max 2."},
}
