PATCHES = {
    ("18-7", 6): {"a": "Publishers had said no.", "g": "Accept: publishers said no / no publisher wanted it / she wanted her friends and family to have the book."},
    ("21-7", 3): {"opts": ["A tool that brings up water", "A kind of toy for the garden", "A gate at the end of a path", "A bucket for carrying sand"]},
    ("21-7", 7): {"items": ["Anne Sullivan came to live with the Keller family in 1887.", "Helen learned the word water at a pump.", "Braille is read with the eyes.", "Helen wrote many books."]},
    ("21-7", 11): {"opts": ["Helen Keller was born in Alabama in the year 1880.", "Helen Keller achieved much with her teacher’s help.", "Anne Sullivan liked to teach Helen by using a doll.", "Braille is a way of reading with the fingertips."]},
    ("22-7", 2): {"q": "In paragraph 2, what does “expedition” mean?", "opts": ["A kind of hut where climbers can rest", "A long trip with a special aim", "A heavy bag for carrying food", "A map showing the way up"]},
    ("22-7", 11): {"opts": ["They wear much warmer coats and boots than others.", "They carry far less food and gear than others.", "They know the paths and are used to the cold.", "They had already been to the top of Everest."]},
    ("22-7", 12): {"opts": ["Mount Everest is the highest mountain on Earth.", "The team carried food and tents up the mountain.", "Darjeeling is a town in the country of India.", "Tenzing Norgay helped a team climb Everest."]},
    ("23-7", 2): {"opts": ["A kind of race for wheelchairs", "A type of racing wheelchair", "A condition of the spine", "A prize given to sportspeople"]},
    ("23-7", 10): {"opts": ["To show how good she was at racing", "To show how many races she entered", "To show that her races were quite short", "To explain how a racing chair is built"]},
    ("23-7", 12): {"opts": ["Tanni Grey-Thompson was born in Cardiff in 1969.", "A racing wheelchair has two large back wheels.", "The Paralympic Games were held in Seoul in 1988.", "Tanni became a great racer and helped others."]},
    ("24-7", 3): {"opts": ["Brave and daring", "Old-fashioned and dull", "Very quiet and shy", "Rather silly and foolish"]},
    ("24-7", 9): {"opts": ["Much faster than others", "Painted in bright colours", "Invented in a story", "Written down on paper"]},
    ("24-7", 10): {"a": "Fogg took eighty days and Nellie took a little over 72, so she was about eight days quicker.", "g": "Accept: 80 minus 72 is 8 / she took 72 days but Fogg took eighty / she was a week and more faster."},
    ("24-7", 11): {"q": "Nellie “did not know it at first, but she was in a race”. Explain why this was true."},
    ("25-7", 8): {"opts": ["Easy to do and quick to finish", "Hard and needing great courage", "Cheap for most sailors to try", "Silly and far too dangerous"]},
    ("26-7", 2): {"opts": ["Too tired to carry on", "Frightened and worried", "Completely fascinated", "Bored and fed up"]},
    ("26-7", 9): {"opts": ["A long trip with a goal", "A quick walk to the shops", "A special type of clothing", "A club for mountain lovers"]},
}
TEXT_PATCHES = {
    "18-7": [("Six publishers said no. So in 1901 she had 250 copies printed herself and gave them to her friends and family.",
              "Several publishers said no. So in 1901 she had 250 copies printed herself, for her friends and family.")],
    "19-7": [("given to women who have done", "given to people who have done")],
    "21-7": [("write more than a dozen books", "write many books")],
    "24-7": [("she then went on by train to France", "she then went on to France by train and boat"),
             ("Nellie did not know it, but she had been in a race.", "Nellie did not know it at first, but she was in a race.")],
    "25-7": [("and she was the youngest person ever to finish it", "and at that time she was the youngest person to have finished it"),
             ("set up a charity, the Ellen MacArthur Cancer Trust, which takes", "set up a charity which takes")],
}
