PATCHES = {
    # ---------- MC: correct option no longer the longest ----------
    ("33-1", 10): {"opts": ["It was loud and confident, ready to be heard.", "It sounded strange because she was nervous.", "It was sharp and angry with the judge.", "It was hoarse from all the cheering earlier."]},
    ("33-1", 11): {"opts": ["A careless mistake made in a hurry", "A quiet murmur from the crowd", "A showy, dramatic movement", "A sudden pause before speaking"]},
    ("33-1", 14): {"opts": ["Hopeful, then guilty, then determined", "Bored, then delighted, then furious at last", "Frightened, then relieved, then very proud", "Confident, then careless, then sleepy"]},
    ("33-2", 10): {"opts": ["Calmness under pressure", "Loud, angry complaint", "Great speed of thought", "Deep confusion and worry"]},
    ("33-2", 12): {"opts": ["She was very fortunate, and her skill counted for very little.", "She was patient and noticed small things others missed.", "She wanted to become famous as quickly as she possibly could.", "She doubted her own results and felt uncertain."]},
    ("33-2", 13): {"opts": ["A large telescope was built in a field near Cambridge.", "A student’s careful attention to a small mark led to a discovery.", "Scientists once received a friendly message from a faraway planet.", "Prizes are always shared fairly between scientists."]},
    ("33-3", 1): {"opts": ["It was sudden and alarming to everyone nearby.", "It was steady and passed along the street.", "It was faint and very difficult to hear clearly.", "It was out of time and hard to follow."]},
    ("33-3", 9): {"opts": ["Away from where it belongs", "Unusually large and heavy", "Bright and eye-catching", "Beautifully and carefully made"]},
    ("33-3", 11): {"opts": ["She was very tired and wanted some peace and quiet at last.", "She was now paying attention to the rhythm and its meaning.", "She was afraid of the noise of the looms and wanted to leave.", "She could not hear anything over the noise."]},
    ("33-3", 12): {"opts": ["Never stop to talk to your neighbours while you work.", "Cloth should always be woven as quickly as possible.", "Mistakes can lead to new ideas if you are patient.", "Old designs are always better than new ones."]},
    ("33-4", 2): {"opts": ["Melted away slowly over time", "Pressed firmly together", "Carried away by the wind", "Divided into thin layers"]},
    ("33-4", 12): {"opts": ["To describe how moraines are made from ice and rock", "To show that these features can still be seen in Britain", "To explain how erratics travel long distances", "To compare the shapes of river valleys and glacial valleys"]},
    ("33-4", 13): {"opts": ["Glaciers are made of snow and move very slowly down valleys.", "Rivers and glaciers carve mountain land in exactly the same way as one another.", "Moving ice shapes mountain landscapes and leaves features behind.", "Erratics are the most important of all glacial features."]},
    ("33-5", 3): {"opts": ["They were perfectly smooth and polished all over.", "They were dotted with patches of colour.", "They were brand new and very clean.", "They were covered in a layer of snow."]},
    ("33-5", 10): {"opts": ["Cleared it away forcefully", "Painted it a different colour", "Invited it to stay a while", "Buried it quietly underground"]},
    ("33-5", 12): {"opts": ["To describe the weather and the countryside around the wall", "To show Kwesi is doubtful and set up what happens next", "To explain how and why the wall was originally built", "To give directions to the next fort along the route"]},
    ("33-5", 13): {"opts": ["Bored and restless", "Cross and tired", "Frightened", "Thoughtful"]},
    ("33-5", 14): {"opts": ["A sibling argument about a guidebook that spoils a long day out", "A history of the Roman Empire and the soldiers who once guarded its frontier", "A description of a ruined fort and the land around it", "A walk along a Roman wall that changes how a boy and the writer see it"]},
    ("33-6", 2): {"opts": ["It had grown louder and more excited.", "It had given way and faded to quiet.", "It had been recorded to play later.", "It had been ignored by the players."]},
    ("33-6", 10): {"opts": ["It was very old and falling apart.", "It was huge and hollow inside.", "It was damp and cold inside.", "It was crowded with people."]},
    ("33-6", 12): {"opts": ["To suggest it was broken and was in need of repair", "To show it displayed a result nobody was left to see", "To say that it was very bright and could be seen for miles", "To explain how it was powered through the night"]},
    ("33-6", 13): {"opts": ["From excitement, to calm, to quiet rest", "From fear, to anger, then to relief", "From boredom, to surprise, then to joy", "From sadness, to panic, then to laughter"]},
    ("34-1", 1): {"opts": ["A sudden surprise for everyone", "A game played with strict rules", "A private secret kept by a family", "A habit repeated in the same way"]},
    ("34-1", 9): {"opts": ["He was trying to hide his feelings.", "He had hurt his hand on a rusty nail.", "He was angry with Amara for arguing.", "He was tired from all the packing."]},
    ("34-1", 10): {"opts": ["To check whether the wood is still damp from paint", "To hold on to the memories before they leave", "To measure exactly how much Amara has grown", "To show that he is cross about the paint"]},
    ("34-1", 13): {"opts": ["Amara is angry with her parents for moving house.", "Amara and her father find a way to keep their memories.", "Amara decides to hide the pencil lines from the new owners.", "Amara’s father agrees to take the door with them."]},
    ("34-2", 1): {"opts": ["Ashamed of these effects", "Free from these effects", "Pleased with these effects", "Unaware of these effects"]},
    ("34-2", 12): {"opts": ["Angry and completely dismissive", "Respectful but unconvinced", "Amused and rather mocking", "Worried and very uncertain"]},
    ("34-2", 13): {"opts": ["To explain how bulbs and lamps are made and used", "To describe how birds and insects find their way at night", "To give a history of street lighting in towns", "To persuade readers to reduce careless outdoor lighting"]},
    ("34-3", 1): {"opts": ["A hopeful wish", "A helpful hint", "A polite request for help", "A firm final judgement"]},
    ("34-3", 10): {"opts": ["Repairs should be finished as quickly as they possibly can be.", "Old books should always be replaced with brand new ones.", "A repaired book should look as good as new again.", "The aim is to keep the book working, not to hide its age."]},
    ("34-3", 13): {"opts": ["A child learns patience and care from a teacher who values quiet work.", "A child dislikes their dad’s choice of Saturday activity and refuses to go back.", "A woman asks a bookbinder to mend a Bible that is very old.", "A bookbinder decides to sell his workshop to a young apprentice."]},
    ("34-4", 8): {"opts": ["The dangers of wildfires in dry forests", "How birds carry seeds to new places", "Extra signals that some seeds wait for", "Why moisture is so important"]},
    ("34-4", 11): {"opts": ["Date palms grow much faster than other plants", "Some seeds can stay alive for a very long time", "Scientists can make old seeds sprout almost instantly", "Fortresses are good places to grow plants"]},
    ("34-4", 14): {"opts": ["Plants always grow far better in warm places than in cold ones.", "Seeds need only water and sunlight to sprout.", "Scientists have found very old seeds in Israel.", "Seeds wait for the right signals, which helps them survive."]},
    ("34-5", 10): {"opts": ["The cleaner has worked in many different countries.", "The tune is very loud and can be heard from far along the platform.", "The cleaner is a famous singer from another country.", "The words are lost, leaving something anyone could feel."]},
    ("34-5", 13): {"opts": ["A quiet station fills with travellers, then falls still again.", "A cleaner finds a lost glove and tries to return it to its owner.", "A girl is frightened of travelling on her own for the first time.", "A train is late and the passengers become annoyed."]},
    ("34-6", 1): {"opts": ["Carefully checked over twice", "Praised and widely copied", "Not noticed or given credit", "Hidden away on purpose"]},
    ("34-6", 10): {"opts": ["It explains why Ada left London.", "It describes Ada’s notes and their purpose.", "It explains how Babbage built his first machine.", "It lists Ada’s hobbies as a child."]},
    ("34-6", 13): {"opts": ["Ada Byron lived in London and wrote many long letters to her friends.", "Charles Babbage built the first working computer in England.", "Lord Byron was a famous poet who left England.", "Ada saw early what computers could become, and was valued later."]},

    # ---------- Two-mark questions kept (made explicit) ----------
    ("33-1", 13): {"q": "What do you think Imani is about to do? Give a prediction and one piece of evidence from the last two paragraphs.",
                   "g": "1 mark for a sensible prediction (she will admit or confess about the bucket). 1 mark for a piece of evidence from the last two paragraphs (“Excuse me”, she took a step, she reached for the corner of the cloth). Max 2."},
    ("33-2", 14): {"g": "1 mark for each of two sensible points supported by the text (examined every centimetre of chart; remembered and checked the odd mark; asked for a faster recording; kept searching and found more signals; gave her prize money to students). Max 2."},
    ("33-5", 7): {"g": "1 mark for each of two pieces of evidence (began to count his own steps; stopped complaining; gazed north; asked what it would have been like to stand there). Max 2."},

    # ---------- Two-mark questions converted to 1 mark ----------
    ("33-1", 4): {"m": 1, "q": "Why did Imani’s stomach lurch when the judge reached her sunflower?",
                  "a": "She suddenly realised the sunflower was standing on a hidden bucket, which would make it seem taller than it really was.",
                  "g": "Accept the idea that the hidden bucket / raised pot would make her sunflower measure taller than it really was (so the result would be unfair). “The bucket” with some sense of the unfair height is enough. Do not accept “she was nervous” on its own."},
    ("33-1", 6): {"m": 1, "q": "Dev’s smile “arrived slowly, as if it had been fetched from somewhere a very long way off”. What does this suggest about how Dev felt?",
                  "a": "He was disappointed but trying to hide it, so the smile took great effort.",
                  "g": "Accept disappointed / sad / upset but pretending to be pleased, or the smile being forced or an effort."},
    ("33-2", 4): {"m": 1, "q": "In paragraph 3, why did Bell not dismiss the “bit of scruff” as most observers would have done?",
                  "a": "She remembered seeing the same mark in the same place before.",
                  "g": "Accept remembering the mark had appeared before or in the same place, or checking her earlier charts and finding it again."},
    ("33-2", 6): {"m": 1, "q": "How did Bell work out that the signal was probably not interference from cars or machinery?",
                  "a": "It appeared at the same point in the sky each time, following the stars rather than the clock.",
                  "g": "Accept the signal appearing at the same point in the sky each time, or keeping to the stars rather than the human working day."},
    ("33-2", 7): {"m": 1, "q": "In paragraph 5, the writer puts “speaking” in quotation marks. Why?",
                  "a": "The signals were not really speaking; the writer is treating the idea of messages lightly, as something unlikely.",
                  "g": "Accept the idea that the word is not literal (the signals are not real speech), or that the writer is treating the idea as unlikely or a bit absurd."},
    ("33-3", 4): {"m": 1, "q": "“To her it glared like a drop of ink spilled across a clean white page.” What does this comparison suggest about how Abena felt about the mistake?",
                  "a": "The mistake seemed very obvious and shameful to her, even though it was small.",
                  "g": "Accept that the mistake stood out very clearly to her, or that she felt embarrassed or ashamed of it."},
    ("33-3", 7): {"m": 1, "q": "What does Abena’s grandfather’s reaction to the mistake show about his character?",
                  "a": "He is kind, patient and wise: he does not scold her but shows her how to turn the mistake into a new pattern.",
                  "g": "Accept any suitable trait: kind, patient, wise, gentle, calm, encouraging. The answer must name a quality, not just describe what he did."},
    ("33-4", 5): {"m": 1, "q": "Use paragraph 3 to explain in one sentence how plucking removes rock from the ground.",
                  "a": "Meltwater freezes in cracks and grips pieces of rock, which are pulled away as the glacier moves on.",
                  "g": "Accept one clear explanation: water freezes onto the rock and the moving glacier pulls it away. Accept “the glacier freezes onto the rock and drags it off”."},
    ("33-4", 6): {"m": 1, "q": "Use paragraph 4 to explain one reason why glacial valleys are wider than river valleys.",
                  "a": "A glacier is a huge slab that cannot bend around obstacles, so it scours the sides as well as the floor.",
                  "g": "Accept any one of: a glacier scours the sides as well as the floor; a glacier is a huge slab that cannot wind around obstacles; a river cuts mainly downwards."},
    ("33-5", 4): {"m": 1, "q": "The wall is described as “the spine of some enormous sleeping animal”. What impression does this give of the wall?",
                  "a": "It is huge and long, like the back of a giant creature, still and powerful.",
                  "g": "Accept any one idea: very big or long; shaped like a creature’s back; still or calm but alive or powerful."},
    ("33-5", 11): {"m": 1, "q": "Look at the final paragraph. “It seemed to me that it was no longer only a wall.” What does the writer now think the wall is?",
                   "a": "Something made by people that links the present to the past.",
                   "g": "Accept the idea that the wall stands for people, effort or history (for example a link to the soldiers, or work done by careful hands)."},
    ("33-6", 4): {"m": 1, "q": "In paragraph 1, the writer describes the crowds as pouring through the turnstiles “in noisy tributaries”. What does this comparison suggest about the crowds?",
                  "a": "They moved like streams flowing together into a river: many small groups joining into one flow.",
                  "g": "Accept crowds flowing like water or streams, or many small groups joining together into one large crowd."},
    ("33-6", 7): {"m": 1, "q": "Why do you think the writer says the emptiness “felt strangely full”?",
                  "a": "The things left behind (scarves, a glove, a programme) show the people who had been there, so it still felt full of them.",
                  "g": "Accept the idea that traces or memories of the crowd remained, with or without an example from paragraph 2."},
    ("33-6", 9): {"m": 1, "q": "The groundskeeper presses the turf back “as gently as if tucking a child into bed”. What does this simile suggest about the groundskeeper?",
                  "a": "The groundskeeper is gentle and caring towards the pitch.",
                  "g": "Accept gentle, caring, tender or patient, or that the groundskeeper treats the pitch as precious."},
    ("34-1", 8): {"m": 1, "q": "Amara thinks that painting over the marks is “a curious way of announcing that it had never mattered”. What does this tell you about how she feels?",
                  "a": "She is hurt because she believes the marks matter and should not be covered up as if they meant nothing.",
                  "g": "Accept a suitable feeling (hurt, sad, unhappy, protective) linked to the marks mattering to her."},
    ("34-1", 11): {"m": 1, "q": "The author describes the marks as “a diary composed in a language that only the door could read”. What does this suggest about the marks?",
                   "a": "They are a private record of Amara’s childhood that only the family would understand.",
                   "g": "Accept either idea: they record the story of growing up, like a diary; or they are private or personal and hard for others to understand."},
    ("34-2", 8): {"m": 1, "q": "Explain why the writer says an upward-shining lamp “illuminates nothing that needs illuminating”.",
                  "a": "Nothing useful, such as a path or road, is lit; the light is wasted in the sky.",
                  "g": "Accept the idea that no useful place or thing is lit, or that the light is wasted or lost into the sky."},
    ("34-2", 11): {"m": 1, "q": "“The stars have not gone anywhere; we have merely hidden them.” What does this suggest about who is responsible for the loss of the stars?",
                   "a": "People are responsible: we have hidden the stars ourselves.",
                   "g": "Accept people, humans or “we” (our lighting) being to blame. A comment that it can be put right may be added but is not needed."},
    ("34-3", 7): {"m": 1, "q": "When the narrator gave answers, “He waited.” Why do you think Mr Iqbal waited rather than simply explaining what was wrong?",
                  "a": "He wanted the narrator to work it out for themself, so that they would learn.",
                  "g": "Accept the idea that he wanted the narrator to think or find the answer, or that this helps them learn, build skill or gain confidence."},
    ("34-3", 9): {"m": 1, "q": "The narrator began to hear the word “Again” “less as a verdict than as an invitation”. What does this show about how the narrator now felt when told “Again”?",
                  "a": "Encouraged: it felt like a chance to improve, not a judgement.",
                  "g": "Accept encouraged, or given a chance to improve or try again, rather than criticised or told off."},
    ("34-3", 12): {"m": 1, "q": "The narrator says the words of thanks “would not bind”. Why could the narrator not say thank you?",
                   "a": "The narrator was too overcome with feeling to find the words.",
                   "g": "Accept strong emotion, shyness or being lost for words. Also accept a link to “bind” as words that would not hold together like pages."},
    ("34-4", 7): {"m": 1, "q": "Explain why tiny seeds often need light before they sprout.",
                  "a": "They hold little food, so they must be near the surface to reach the sun before their supplies run out.",
                  "g": "Accept the idea of having little stored food, or of needing to be close to the surface to reach sunlight quickly."},
    ("34-5", 8): {"m": 1, "q": "The woman clutches her briefcase “against her chest as if it were a shield”. What does this suggest about how she feels?",
                  "a": "She feels nervous or defensive, and holds the briefcase like protection.",
                  "g": "Accept a suitable feeling (worried, nervous, tense, guarded), with or without a link to protection."},
    ("34-5", 11): {"m": 1, "q": "“Every head lifts at once, like a field of flowers turning to a change in the light.” What does this simile show about the passengers?",
                   "a": "They all react together, drawn hopefully towards the board.",
                   "g": "Accept either idea: they move or react together at the same moment; or they are hopeful, eager or drawn to something."},
    ("34-6", 9): {"m": 1, "q": "Why does the writer call Ada’s idea about music “a huge leap”?",
                  "a": "Machines were thought of as little more than adding tools, but Ada imagined one could make music.",
                  "g": "Accept the idea that others saw machines only as calculators, or that Ada saw much further (for example making music)."},
    ("34-6", 11): {"m": 1, "q": "The writer ends, “She was not a builder of machines; she was something rarer.” Explain what the writer means.",
                   "a": "Ada did not build machines, but she had the rare vision to foresee what they could become.",
                   "g": "Accept vision, foresight or imagining what machines could become. “She did not build machines” on its own is not enough."},
    ("33-7", 4): {"m": 1, "q": "In paragraph 3, the writer says that writing to Hardy was “something bold”. Why was it bold?",
                  "a": "He had no university education and was an unknown clerk writing to a famous Cambridge mathematician.",
                  "g": "Accept any one reason: he was unknown or had no university education; Hardy was a well-known Cambridge mathematician; he sent theorems he had not proved."},
    ("34-7", 5): {"m": 1, "q": "In paragraph 4, the writer says a tree is “not a decoration but a working part of the land”. Explain what the writer means.",
                  "a": "A tree does useful jobs, such as holding the soil, giving firewood and food and protecting water, so it is more than something to look at.",
                  "g": "Accept the idea that trees do useful jobs or are not just for looks. A correct example from the paragraph is also enough."},
    ("34-7", 14): {"m": 1, "q": "The writer begins with a general statement about what happens when a landscape loses its trees before mentioning Maathai. Why might the writer have chosen to begin this way?",
                   "a": "It introduces the problem Maathai worked on, so that her solution seems important.",
                   "g": "Accept introducing the problem or topic, making the reader curious, or leading to why Maathai’s work mattered."},
    ("34-8", 6): {"m": 1, "q": "Use paragraph 3 to explain why the firm that Mandela and Tambo opened was important.",
                  "a": "It was the first law firm in the country run by Black partners, and it helped people who were treated unfairly.",
                  "g": "Accept either idea: it was the first law firm run by Black partners; or it helped people who had been treated unfairly or needed a lawyer."},
    ("34-8", 14): {"m": 1, "q": "The last paragraph mentions again “a boy who was given a new name at school”. Why do you think the writer finishes by referring back to the beginning?",
                   "a": "It shows how far Mandela travelled from his small beginnings to the highest office, and it gives a neat ending.",
                   "g": "Accept either idea: it shows the contrast between the beginning and the end (how far he went); or it links the ending to the start and finishes neatly."},
}
