PATCHES = {
    ("24-1", 1): {"opts": ["Their sharp eyesight", "Their flapping wings", "Echoes from their calls", "Bright light from the moon"]},
    ("24-1", 3): {"opts": ["Where bats like to sleep", "Why moths are hard to see at night", "Bats compared with other mammals", "How a bat makes and uses sound"]},
    ("24-1", 4): {"opts": ["Time spent waiting", "How fast something moves", "A sudden loud noise", "How far away it is"]},
    ("24-1", 12): {"opts": ["Bats are dangerous animals that hunt small creatures at night.", "Ships and dolphins are much better than bats at finding things.", "Bats use echoes to find their way and food in the dark.", "Moths are the only food that bats ever eat."]},
    ("22-2", 2): {"opts": ["Jump very high", "Move smoothly", "Sink down slowly", "Swim very fast"]},
    ("22-2", 11): {"opts": ["How to dig a new pond in a garden", "Birds that visit the pond", "Animals at the pond bottom", "Plants that float on top"]},
    ("22-3", 4): {"opts": ["A note from Nani", "Some crumbs and scratches", "A broken plate and a spoon", "A trail of sugar grains"]},
    ("22-3", 7): {"opts": ["Sat down on the cold floor", "Fell over with a loud bump", "Ate up all the crumbs", "Ran with quick tiny steps"]},
    ("22-3", 12): {"opts": ["Two cousins argue, then find who took the biscuits.", "Nani forgets how to count and bakes a new batch.", "Ravi loses his notebook somewhere in the busy kitchen.", "A burglar breaks into Nani’s house in the night."]},
    ("22-4", 3): {"opts": ["Breaking into pieces", "Fitting together", "Getting very dirty", "Moving very quickly"]},
    ("22-4", 9): {"opts": ["It has two bumps on the same side.", "It has a hollow on both sides.", "It is made only of hard metal.", "It has one bump and one hollow."]},
    ("22-5", 5): {"opts": ["Worried or scared", "Tired and sleepy", "Hungry and thirsty", "Cross and angry"]},
    ("22-5", 11): {"opts": ["A child wins every single race at Sports Day.", "Being kind mattered more than winning.", "Team Yellow is the best team in the school.", "Ben was too slow to finish the race."]},
    ("22-6", 3): {"opts": ["Lasting a short time", "Larger than the others", "Dangerous to touch", "Lasting for many years"]},
    ("22-6", 12): {"opts": ["Catching and returning animals", "Finding crabs and shells on the beach", "Walking carefully on wet rocks", "What to pack in your beach bag"]},
    ("23-1", 1): {"opts": ["In the big school hall", "In the old town hall", "In Kofi’s front room", "In a busy music shop"]},
    ("23-1", 11): {"opts": ["Quiet jobs can matter even when nobody notices.", "Pianos are too difficult for most people to tune.", "Kofi should learn to play the piano very well.", "Noisy jobs are always the best kind."]},
    ("23-2", 1): {"opts": ["To stop boats from sinking in deep water", "To let boats climb up and down hills", "To make canals deeper and wider", "To keep the canal water clean"]},
    ("23-2", 2): {"opts": ["A small rowing boat", "A heavy wooden gate", "An enclosed space", "A long metal pipe"]},
    ("23-2", 9): {"opts": ["The boat has to sail much faster to climb.", "When the water is level, the gate can be opened.", "Canals are always completely flat and very straight.", "The lock keeper goes home after work."]},
    ("23-3", 2): {"opts": ["Thin curling stems that help plants climb", "Large flat leaves that soak up the sunlight", "Drops of water on the leaves", "Metal supports for tall plants"]},
    ("23-3", 11): {"opts": ["Grandpa Joe grows many plants, including an orchid.", "The glasshouse roof leaks whenever it rains heavily.", "The narrator dislikes tomatoes and cucumbers.", "Grandpa Joe is going to sell his plants."]},
    ("23-4", 2): {"opts": ["Mixed up and unclear", "Very loud and sharp", "Easy to hear clearly", "A long way away from us"]},
    ("23-4", 10): {"opts": ["They are ordinary things used to make other sounds.", "They are hidden away from the audience in the studio.", "They are much louder than real sounds.", "They are recorded by the actors on set."]},
    ("23-4", 11): {"opts": ["Where to buy coconuts for a film", "Objects that make film sounds", "The life of Jack Foley long ago", "How to make a whole film"]},
    ("23-5", 2): {"opts": ["It was full of flying insects.", "It was quiet and calm.", "It was full of excitement.", "It was empty and still."]},
    ("23-5", 11): {"opts": ["Dogs should never be allowed to run on beaches.", "Winning is the only thing that really matters.", "Sandcastles should always be built far away from the sea.", "Clever thinking can turn a problem into a success."]},
    ("23-6", 2): {"opts": ["Old coins and jewels buried long ago in the ground", "Remains of living things that turned to stone", "Tools that people use to dig up rocks", "Rocks that glow in the dark"]},
    ("23-6", 11): {"opts": ["Because it shows the bones could easily break", "Because it shows she was afraid of the skeleton", "Because it shows she was bored with digging", "Because it shows she worked very fast"]},
    ("23-6", 12): {"opts": ["Mary Anning’s father made furniture and sold it in town.", "Mary Anning became a fossil hunter from a poor family.", "Ichthyosaurs were large animals that lived in the sea.", "Lyme Regis is a small town on the south coast."]},
    ("24-2", 1): {"opts": ["She wanted to marry the prince.", "She needed shelter because her cart had broken.", "She had come to sell honey to the Queen herself.", "She had been invited to a royal feast."]},
    ("24-2", 6): {"opts": ["Amused and delighted", "Upset and disappointed", "Tired and very hungry", "Fast asleep and dreaming"]},
    ("24-2", 12): {"opts": ["A queen was tricked by a clever maid who had a secret plan.", "A prince wanted to grow a giant pea plant in the palace gardens for the queen.", "A tired traveller showed that kindness matters more than a test.", "A cart broke down in a storm and the wheel was lost."]},
    ("24-3", 4): {"opts": ["Very hot and glowing red", "Firm and not a liquid", "Very old and worn away", "Full of flowing water"]},
    ("24-3", 11): {"opts": ["To show that Venus is soft and cosy to walk on", "To help us picture heat being kept in", "To show that Venus is a bedroom", "To explain why Venus is blue"]},
    ("24-3", 12): {"opts": ["Voyager 2 is the fastest spacecraft that was ever built.", "Scientists learn about planets by sending probes.", "Only Uranus and Neptune have been photographed.", "Space is too dark and cold to explore."]},
    ("24-4", 6): {"opts": ["Loudly and very proudly", "Very quickly and quietly", "In an embarrassed way", "Without any interest"]},
    ("24-4", 11): {"opts": ["A little girl ended an argument by showing her skill.", "Three friends lost their den in a terrible storm.", "Yusuf built a den all by himself one summer.", "Poppy wanted to move the den to a much bigger garden nearby."]},
    ("24-5", 3): {"opts": ["Paints colours onto the rocks", "Fills up the space with soil", "Covers over the top with mud", "Wears away to make a shape"]},
    ("24-5", 12): {"opts": ["Rivers are only found high up in mountains and hills.", "A river changes on its way to the sea, and its water is used again.", "Silt is the most important thing that a river carries along to the sea.", "Rain only falls on hills and mountains far from the sea."]},
    ("24-6", 2): {"opts": ["She was visiting a friend.", "She was working extra hours in a shop.", "She had a secret woodwork project.", "She was going to the park."]},
    ("24-6", 3): {"opts": ["A game that children play together", "An idea that explains something", "A loud noise in the night", "A mistake that people make"]},
    ("24-6", 11): {"opts": ["The loft looked very different now.", "Daniel had never once been inside the house.", "The loft was in the dark.", "Daniel had forgotten his glasses."]},
}
