PATCHES = {
    # 27-7 Seacole: key was the longest option
    ("27-7", 14): {"opts": ["A Jamaican traveller cared for soldiers and is now honoured.",
                            "A Scottish soldier wrote a book about his adventures in Jamaica.",
                            "A hotel owner spent all her life in one town in Jamaica.",
                            "A nurse was welcomed by everyone she asked for work."], "a": "A"},
    # 28-7 Jemison
    ("28-7", 3): {"opts": ["Full of excitement", "Eager to learn", "Good at sport", "Quiet and shy"], "a": "B"},
    ("28-7", 14): {"opts": ["Space shuttles are very fast and can circle the Earth in eight days.",
                            "A doctor followed her curiosity into space and then helped others learn.",
                            "Frog eggs and bone cells can grow only in space, far above the ground.",
                            "Chicago is a good place to learn about science and to read library books."], "a": "B"},
    # 29-7 Coleman
    ("29-7", 3): {"opts": ["Worried about it", "Puzzled by it", "Tired of it", "Firmly decided"], "a": "D"},
    ("29-7", 11): {"g": "Accept any answer about fairness, equality or everyone being welcome, or about her refusing to perform where Black people were kept out."},
    ("29-7", 12): {"opts": ["A busy family in Texas", "Returning to New York", "Rules for pilots", "Training in France"], "a": "D"},
    ("29-7", 13): {"a": "It might have encouraged them / shown them it was possible, because Bessie earned a licence even though the flying schools in the United States had refused her.",
                   "g": "1 mark for a sensible prediction (inspired, encouraged, gave hope). 1 mark for a reason from the text (she was the first, she succeeded even though she was refused, she hoped to open a flying school for others)."},
    ("29-7", 14): {"opts": ["Bessie Coleman lived in Texas and Chicago all her life and never travelled far.",
                            "Bessie Coleman worked as a manicurist and later taught French to young pilots.",
                            "Bessie Coleman was turned away, learned to fly in France and became a pilot.",
                            "Bessie Coleman built the first biplane in the small town of Le Crotoy."], "a": "C"},
    # 30-7 Johnson
    ("30-7", 1): {"opts": ["A machine that stored many numbers", "A person who did sums by hand", "A room where engineers met", "A tool for flying spacecraft"], "a": "B"},
    # 31-7 Garrett Anderson
    ("31-7", 9): {"q": "In paragraph 4, the author calls the dispensary “a modest beginning”. What does this suggest about the dispensary at first?",
                  "a": "It was small / not grand, but it was somewhere to start.",
                  "g": "Accept small, simple, humble or not very big. Do not accept “failed” or “unimportant”."},
    ("31-7", 13): {"opts": ["Elizabeth trained as a nurse in London and stayed a nurse for the rest of her life.",
                            "Elizabeth found another way to become a doctor when schools turned her away.",
                            "Elizabeth changed the rules of the Society of Apothecaries to help other women.",
                            "Elizabeth studied Latin and Greek at a university and then became a teacher."], "a": "B"},
    # 32-7 Tu Youyou
    ("32-7", 2): {"opts": ["A tiny living thing that makes a person ill", "A kind of plant that is used to make medicine",
                           "A machine that is used to find germs in water", "A doctor who treats people with fevers"], "a": "A"},
    ("32-7", 5): {"items": ["Tu found the clue about soaking the plant in water.", "Tu was asked to lead a research team.",
                            "Tu was awarded the Nobel Prize.", "Tu’s team prepared 380 plant extracts."]},
    ("32-7", 6): {"items": ["Tu began her search by reading old medical books.", "Every extract worked well against the parasite.",
                            "Ge Hong’s text advised soaking the plant in water.", "Tu won the Nobel Prize in 1972."]},
    ("32-7", 12): {"opts": ["Very old", "Widely admired", "Easy to win", "Costing a lot of money"], "a": "B"},
    ("32-7", 13): {"opts": ["Malaria has always been easy to treat with the medicines we have today.",
                            "Tu Youyou and her team searched old books and found a malaria medicine.",
                            "Scientists should never read old books because they are out of date now.",
                            "Ge Hong invented artemisinin in 1972 and won a Nobel Prize for it in 2015."], "a": "B"},
    ("32-7", 14): {"a": "Old books gave her a clue (to soak the plant in water, not boil it), and modern testing showed which plant and method worked; they helped each other.",
                   "g": "1 mark for explaining the idea (old knowledge and testing combined). 1 mark for an example (Ge Hong’s text and its clue about not heating the plant, plus testing extracts on mice)."},
    # 33-7 Ramanujan: he was 30 in May 1918, so the age question is replaced
    ("33-7", 6): {"items": ["Ramanujan sailed from India.", "Ramanujan was elected a Fellow of the Royal Society.",
                            "Ramanujan wrote a letter to Hardy.", "Hardy replied to Ramanujan’s letter."]},
    ("33-7", 10): {"opts": ["They are still useful to mathematicians.", "They have never been read by anyone else.",
                            "They were written in a code that nobody can read.", "They were written for schoolchildren."], "a": "A"},
    ("33-7", 11): {"q": "In which year did Ramanujan receive his degree of Bachelor of Arts by Research?", "a": "1916.", "g": "Accept 1916 only."},
    ("33-7", 14): {"a": "He was elected a Fellow of the Royal Society; he was elected a Fellow of Trinity College.",
                   "g": "1 mark each. Accept Fellow of the Royal Society / Fellow of Trinity College. Max 2."},
}
TEXT_PATCHES = {
    "27-7": [("In 1855, soldiers from Britain were staying", "By 1855, soldiers from Britain were staying"),
             ("Mary also visited soldiers who needed care and sold medicines to them.", "Mary also went out to care for soldiers who were ill or wounded."),
             ("Her story has been taught in schools since 2007.", "In 2007, her story was added to the national curriculum in England.")],
    "28-7": [("Studies like these can help scientists to understand how to keep people healthy on long journeys.",
              "The test subjects included the crew themselves, as well as fish, fruit flies and frogs.")],
    "29-7": [("began French lessons in the evenings and saved money", "began to learn French and saved money"),
             ("Bessie sailed across the Atlantic Ocean to France.", "Bessie sailed from New York across the Atlantic Ocean to France."),
             ("Every day she studied how aeroplanes work as well as how to fly them.", "There she began the long task of learning to fly."),
             ("She had completed her training in about seven months, and", "She had earned it in about seven months, and"),
             ("Bessie returned to New York in September 1921,", "After almost a year away, Bessie returned to New York in September 1921,"),
             ("where newspaper reporters were waiting to greet her", "where Black and white newspaper reporters were waiting to greet her"),
             ("She refused to take part in any event that kept Black people out, insisting that everyone should be welcome. Having found the first doors closed to her, she used her fame to open others for the people who came after her.",
              "She refused to take part in any event that kept Black people out. She also hoped to open a flying school of her own, where other people could learn to fly.")],
    "30-7": [("the number of dishes and silverware I washed.”", "the number of dishes and silverware I washed …”")],
    "32-7": [("In the middle of the twentieth century, the medicines", "By the 1960s, the medicines"),
             ("It advised soaking the plant in cold water rather than boiling it.", "It advised soaking the plant in water rather than boiling it.")],
    "32-8": [("the pull of gravity just beneath its surface is strong enough that nothing, not even light, can escape.",
              "the pull of gravity close to it is so strong that nothing that falls in, not even light, can escape.")],
    "33-7": [("In May, at the age of 31, he was confirmed as a Fellow of the Royal Society,", "In May, he was elected a Fellow of the Royal Society,")],
    "34-7": [("The prize recognised that caring for the land is linked with fairness, cooperation and peace.",
              "The Nobel committee praised her contribution to sustainable development, democracy and peace.")],
    "34-8": [("In August 1952, Mandela and his friend", "In 1952, Mandela and his friend")],
}
