PATCHES = {
    ("18-1", 7): {"opts": ["Falling right down", "Blowing away", "Sticking out", "Melting away"]},
    ("18-2", 6): {"opts": ["Rushed about very fast and noisily", "Jumped high in the air", "Fell over onto the floor", "Moved slowly and carefully"]},
    ("18-3", 1): {"opts": ["She was ill and needed a rest.", "She had lost her keys again.", "She had worked late all week.", "She had been to a party last night."]},
    ("18-3", 4): {"opts": ["Walked very quietly", "Ran very quickly indoors", "Jumped up and down", "Fell over and got up"]},
    ("18-4", 10): {"opts": ["Why cress is so good for you", "How to grow cress at home", "Which seeds grow biggest", "How to make a sandwich"]},
    ("18-5", 3): {"opts": ["Falling over onto the ground", "Standing completely still", "Growing taller and taller", "Moving gently side to side"]},
    ("18-6", 1): {"opts": ["Only two years or less", "Eight years or more", "Fifty years or more", "Only one year"]},
    ("18-6", 4): {"opts": ["Very hungry and ready to eat", "Very sleepy and tired", "On your own with no company", "Full of energy"]},
    ("18-6", 10): {"opts": ["Rabbits should only eat carrots and sweets every day.", "Rabbits need the right food and water to stay well.", "Rabbits do not need to drink any water at all.", "Rabbits have very small teeth."]},
    ("19-1", 4): {"opts": ["Showed them where to look", "Told them to be quiet", "Took them away from there", "Was cross with them for talking"]},
    ("19-2", 1): {"opts": ["They were ill.", "It was raining hard.", "It was very late.", "They had to tidy their room."]},
    ("19-3", 1): {"opts": ["Sports Day on the field", "Show and Tell day", "Book Week", "School photo day"]},
    ("19-4", 3): {"opts": ["Fly away to a warmer place", "Come together in a group", "Fall asleep", "Look for food"]},
    ("19-4", 10): {"opts": ["How ladybirds catch their food", "Where ladybirds lay their eggs", "Why ladybirds have spots", "How ladybirds spend winter"]},
    ("19-5", 1): {"opts": ["Two hours", "Twenty minutes", "Two days", "Only twenty seconds"]},
    ("19-5", 3): {"opts": ["Broken into small pieces", "Hidden away safely", "Covered on every side", "Tied up tightly with string"]},
    ("19-6", 1): {"opts": ["A kind of white flour", "A hot oven", "A tiny living thing", "A type of coarse salt"]},
    ("19-6", 3): {"opts": ["Growing bigger", "Getting much colder", "Turning brown", "Breaking apart"]},
    ("19-6", 9): {"opts": ["How to shape a round loaf", "What happens in the oven", "Why yeast is small", "How to eat bread"]},
    ("20-1", 2): {"opts": ["Match referee", "Goalkeeper", "Coach", "Defender"]},
    ("20-2", 2): {"opts": ["It moves its eyes around", "It flies backwards", "It turns its whole head", "It hops around"]},
    ("20-3", 8): {"opts": ["Different colours", "Separate parts", "Small holes", "Loose lids"]},
    ("20-3", 10): {"opts": ["Throw all his shells away", "Look for more shells again", "Stay away from the beach", "Give his shells to the shop"]},
    ("20-4", 2): {"opts": ["150 grams", "200 grams", "300 grams", "1000 grams"]},
    ("20-4", 4): {"opts": ["To cut the dough into pieces", "To push and stretch dough", "To heat in a pan", "To pour into a bowl"]},
    ("20-5", 2): {"opts": ["A cheese sandwich", "An apple", "A chocolate biscuit", "Some crisps"]},
    ("20-5", 8): {"opts": ["Bent over", "Spread out", "Splashed about", "Shrank away"]},
    ("20-6", 2): {"opts": ["In the early spring", "In the summer", "In the winter", "In the autumn"]},
    ("20-6", 6): {"opts": ["Big meals shared with friends", "Pretty designs made of shapes", "Clothes made of soft, warm cloth", "Gifts wrapped up in paper"]},
    ("21-1", 2): {"opts": ["It was very long and heavy", "It had a red cover", "It was all about a farmer", "It had a talking parrot"]},
    ("21-1", 4): {"opts": ["Laughing out loud", "Trying hard to remember", "Almost falling asleep", "Getting very cross with him"]},
    ("21-1", 11): {"opts": ["Stop going to the shop", "Help his aunt in the shop", "Sell the parrot book online", "Move away to another town"]},
    ("21-2", 1): {"opts": ["Cold, dry places", "Warm, wet places", "Dry, sandy deserts", "High, snowy mountains"]},
    ("21-2", 4): {"opts": ["Very hot and steamy", "Smooth and soft", "Sticky and gooey", "Crunchy and hard"]},
    ("21-2", 10): {"opts": ["Farmers in Britain grow cacao trees for chocolate.", "Chocolate is only made from milk and sugar in a big factory.", "Chocolate is made from cacao beans in many careful steps.", "Rugby balls are made from cacao pods."]},
    ("21-3", 2): {"opts": ["With a long piece of rope", "With a chalk circle", "With bright orange cones", "With a ruler"]},
    ("21-3", 4): {"opts": ["Move smoothly", "Jump very high", "Roll over and over", "Run very fast"]},
    ("21-4", 4): {"opts": ["Diving deep under the water", "Sitting still on a branch", "Flying fast and low down", "Hiding away in a nest"]},
    ("21-4", 10): {"opts": ["Swallows never build nests of any kind at all.", "Swallows return each year to build mud nests.", "Barns are very dangerous places for swallows.", "Swallows lay all their eggs out at sea."]},
    ("21-5", 2): {"opts": ["A big dragon", "A fish", "A rabbit", "A sun"]},
    ("21-6", 2): {"opts": ["Two", "Four", "Twelve", "Three"]},
    ("21-6", 4): {"opts": ["Wait in a line", "Park in the wrong place", "Race quickly", "Shout loudly"]},
    ("21-6", 11): {"opts": ["Cars are always bad and should be stopped.", "Children should never go to school by car, even when it rains.", "More children should walk to school as it is healthy and fun.", "Walking takes too long."]},
    ("19-7", 1): {"opts": ["Greece", "Germany", "Wales", "France"]},
    ("21-7", 11): {"opts": ["Helen Keller was born in Alabama in the year 1880.", "Helen Keller achieved much with her teacher’s help.", "Anne Sullivan liked to teach Helen new words with a doll.", "Braille is a way of reading with the fingertips."]},
}
