# Book-level comprehension tests. One text, 14 questions, 20 marks each. Question fields:
#  d = content domain (2a vocab, 2b retrieval, 2c summarise/sequence, 2d inference, 2e predict, 2g language)
#  k = find | mc | short | order | tf ; m = marks ; a = model answer ; g = marking guidance
TESTS = []
def T(level, tid, title, ttype, text, qs): TESTS.append(dict(level=level, id=tid, title=title, type=ttype, text=text, qs=qs))
Q2="1 mark for all four correct."
TF="1 mark for all statements correct."

T(18, "18-1", "The Lost Mitten", "Narrative", [
"It was the first snowy morning of winter, and Lily could not wait to go outside. She pulled on her boots, her scarf and her bright red mittens. Then she ran into the garden with her little brother, Sam.",
"The snow was deep and soft, and it sparkled in the sunshine. Lily made a snowball and threw it at the fence. Sam laughed and tried to catch it. Soon they were both covered in snow from head to toe.",
"Next, they decided to build a snowman. Lily rolled a big ball for the body, and Sam rolled a smaller one for the head. Sam ran into the kitchen and came back with a carrot for the nose. Lily found two round pebbles for the eyes.",
"After a while, Lily looked down at her hands. One of her mittens was missing! \u201cOh no,\u201d she said. \u201cI must have dropped it.\u201d",
"Lily and Sam searched all over the garden. They looked under the bench and behind the shed. Lily\u2019s fingers were getting very cold, and she began to feel sad. That mitten had been a present from her gran.",
"At last, Sam saw something red poking out of the snow beside the gate. \u201cFound it!\u201d he shouted, and he pulled it out. It was wet and cold, but it was not lost any more.",
"Lily was so pleased. She gave Sam a big hug and said thank you. Then Mum called from the back door. \u201cCome in, you two! Your cheeks are as red as apples.\u201d Soon they were inside, drinking hot chocolate.",
], [
 dict(d="2a",k="find",m=1,q="Find and copy one word that tells you what the snow felt like.",a="soft",g="Accept \u201csoft\u201d only (\u201cdeep\u201d describes how much snow, not how it felt)."),
 dict(d="2b",k="short",m=1,q="What did Sam fetch from the kitchen for the snowman\u2019s nose?",a="A carrot.",g="Accept carrot."),
 dict(d="2c",k="order",m=1,q="Number the events from 1 to 4 to show the order they happened in the story.",items=["Sam found the mitten.","Lily threw a snowball.","Lily and Sam built a snowman.","Lily saw that a mitten was missing."],a=[4,1,2,3],g=Q2),
 dict(d="2b",k="tf",m=1,q="Tick True or False for each sentence.",items=["Lily rolled the big ball for the snowman\u2019s body.","Sam rolled the big ball for the snowman\u2019s head.","Lily lost her scarf in the garden."],a=["T","F","F"],g=TF),
 dict(d="2d",k="short",m=1,q="Lily and Sam were \u201ccovered in snow from head to toe\u201d. What does this tell you?",a="They were very snowy / they had snow all over them.",g="Accept any answer that shows snow was all over their bodies."),
 dict(d="2d",k="short",m=1,q="Why did Lily begin to feel sad while they searched for the mitten?",a="Her fingers were getting cold / the mitten was a present from her gran.",g="Accept either reason (or both)."),
 dict(d="2a",k="mc",m=1,q="In the story, what does \u201cpoking out\u201d mean?",opts=["Falling down","Blowing away","Sticking out","Melting"],a="C"),
 dict(d="2d",k="short",m=1,q="Why do you think Lily gave Sam a big hug?",a="Because he found her mitten / she was pleased with him.",g="Accept any answer linked to Sam finding the mitten or Lily feeling pleased or thankful."),
 dict(d="2d",k="short",m=1,q="How can you tell that Lily and Sam enjoyed playing in the snow? Give one piece of evidence.",a="Any one of: Sam laughed; Lily could not wait to go outside; they built a snowman; they were covered in snow.",g="Accept any one relevant piece of evidence from the text."),
 dict(d="2g",k="short",m=1,q="Mum said, \u201cYour cheeks are as red as apples.\u201d What does this tell you about Lily\u2019s and Sam\u2019s cheeks?",a="They were very red (because they were cold).",g="Accept red / rosy / cold."),
])

T(24, "24-1", "How Bats Find Their Way", "Explanation", [
"Bats are the only mammals that can truly fly, and most of them come out at night. There are more than a thousand kinds of bat, from tiny bats no bigger than a bumblebee to giant fruit bats with wings over a metre wide. In the dark, it is almost impossible to see, so most bats that hunt insects use a clever trick to find their way. This trick is called echolocation.",
"As a bat flies, it makes high-pitched squeaks that are too high for people to hear. The sounds travel through the air until they hit something, such as a tree, a wall or an insect. Then the sound bounces back to the bat as an echo.",
"The bat\u2019s large ears catch the echo. Its brain works out how long the sound took to return. A short delay means the object is close, while a longer delay means it is further away. The pattern of the echo also tells the bat what shape the object is and whether it is moving.",
"Using echolocation, some bats can find a tiny moth in complete darkness. As the bat gets closer to its prey, it makes its squeaks faster and faster, like a drummer speeding up. This gives the bat a more and more exact picture of where the moth is. Some moths have learned to fight back. They can hear the bat\u2019s squeaks and dive towards the ground to escape.",
"Some bats spend the whole day hanging upside down in caves, then leave together in huge groups at sunset. With thousands of bats squeaking at once, you might think they would get confused, but each bat seems able to pick out its own echoes from all the noise.",
"Echolocation also stops bats from crashing into things. They can even dodge a thin wire! Without this skill, a bat flying through a dark forest would keep hitting the trees. Scientists believe that echolocation helps bats to survive, because it allows them to hunt when there are fewer predators around and less competition for food.",
"People have copied the bat\u2019s trick. Ships use a machine called sonar to send out sounds and listen for the echoes. By timing the echoes, sailors can find out how deep the sea is and whether there are rocks ahead. Dolphins also use echolocation, sending clicks through the water to find fish. It seems that nature invented the idea long before we did.",
], [
 dict(d="2b",k="mc",m=1,q="What do most insect-hunting bats use to find their way in the dark?",opts=["Their eyes","Their wings","Echolocation","Bright light"],a="C"),
 dict(d="2b",k="short",m=1,q="Why can people not hear a bat\u2019s squeaks?",a="They are too high-pitched.",g="Accept: they are too high (for people to hear)."),
 dict(d="2c",k="mc",m=1,q="Which of these is the best heading for paragraph 2?",opts=["Where bats sleep","Why moths are hard to see","Bats and other mammals","How a bat makes and uses sounds"],a="D"),
 dict(d="2a",k="mc",m=1,q="In paragraph 3, what does the word \u201cdelay\u201d mean?",opts=["Time spent waiting","Speed","Loud noise","Distance"],a="A"),
 dict(d="2c",k="order",m=1,q="Number the steps from 1 to 4 to show how echolocation works.",items=["The bat\u2019s ears catch the echo.","The sound bounces back as an echo.","The bat makes high-pitched squeaks.","The bat\u2019s brain works out how far away the object is."],a=[2,3,1,4],g=Q2),
 dict(d="2d",k="short",m=1,q="What would a bat know if an echo came back very quickly?",a="The object is close.",g="Accept: it is near / not far away. Do not accept \u201cit is small\u201d."),
 dict(d="2b",k="tf",m=1,q="Tick True or False for each sentence.",items=["All bats are the same size.","Bats use echolocation to find food.","A bat\u2019s brain catches the echo.","People can easily hear a bat\u2019s squeaks."],a=["F","T","F","F"],g=TF),
 dict(d="2d",k="short",m=1,q="Look at paragraph 4. Why does a bat make its squeaks faster as it gets closer to a moth?",a="To get a more exact picture of where the moth is.",g="Accept: so it knows exactly where the moth is / to track it / to catch it."),
 dict(d="2g",k="short",m=1,q="The author says the squeaks get faster \u201clike a drummer speeding up\u201d. Why does the author make this comparison?",a="To help the reader imagine the squeaks getting faster and faster.",g="Accept any answer about helping the reader picture the increasing speed."),
 dict(d="2d",k="short",m=1,q="Explain one way that echolocation helps bats to survive. Use the text to help you.",a="It helps them find food (insects) in the dark; it stops them hitting trees/obstacles; it lets them hunt when there are fewer predators and less competition.",g="Accept any one way from the text."),
 dict(d="2d",k="short",m=1,q="How is a ship\u2019s sonar similar to a bat\u2019s echolocation?",a="Both send out sounds and listen for the echoes.",g="Accept: both use sound echoes to find out what is nearby / how far away things are."),
 dict(d="2c",k="mc",m=1,q="Which sentence best sums up the whole text?",opts=["Bats are dangerous animals that hunt at night.","Ships and dolphins are better than bats at finding things.","Bats use sound echoes to find their way and their food in the dark.","Moths are the bat\u2019s only food."],a="C"),
])

T(30, "30-1", "The Last Bus", "Narrative", [
"Nadia checked her watch for the third time in as many minutes. The bus shelter was empty except for a crumpled newspaper that skittered across the pavement whenever the wind gusted. Above her, the streetlight flickered and buzzed like a trapped insect. The air smelt of wet stone, as if it might rain at any moment. It was almost half past nine, and the last bus to Wickford was already late.",
"She tugged her coat tighter and glanced at the small suitcase by her feet. Inside, wrapped carefully in tissue paper, was the birthday present she had spent three months saving for: a silver locket, engraved with her grandmother\u2019s initials. Nadia had rehearsed her words all week, yet now they seemed to have deserted her.",
"At last, headlights swept around the corner and the bus wheezed to a halt. The doors folded open with a hiss. The driver, a stocky man with a bristling moustache, drummed his fingers on the steering wheel and peered at her over his glasses. \u201cWhere to, love?\u201d he asked. \u201cWickford, please,\u201d Nadia replied, her voice barely above a whisper.",
"She found a seat by the window and pressed her forehead against the cool glass. Street lamps blurred into streaks of amber as the bus rumbled through the sleeping town. The only other passengers, a sleepy man and a woman with a shopping trolley, barely looked up. Nadia thought about the locket again. She had washed cars, walked the neighbours\u2019 dogs and sold her old books to save enough money. Her mum had warned her that the journey would be long and lonely, but Nadia had insisted. Nothing was going to spoil this surprise.",
"Halfway through the journey, the woman leaned across the aisle. \u201cVisiting family?\u201d she asked, not unkindly. Nadia hesitated. \u201cMy grandmother,\u201d she said at last. \u201cIt\u2019s her seventieth birthday tomorrow, and she thinks I\u2019m at home revising for my exams.\u201d The woman chuckled. \u201cThen you\u2019re in for a treat, love, and so is she.\u201d",
"The bus shuddered to a stop in Wickford, and Nadia stepped down into the cold night air. The village was silent except for the distant hoot of an owl. She hauled her suitcase along a lane fringed with dripping hedges. Her feet ached, and the suitcase seemed heavier with every step. At last the cottage appeared, a single lamp glowing in its window like a beacon.",
"Nadia hesitated at the gate. What if her grandmother was already asleep? What if she was cross at being disturbed so late? Then the front door swung open, and there, silhouetted against the lamplight, stood her grandmother in her dressing gown, peering out into the darkness. \u201cNadia?\u201d she whispered. \u201cIs that really you?\u201d Her voice trembled, and in the lamplight Nadia could see that her eyes were shining.",
"All the words Nadia had rehearsed so carefully evaporated once more, but this time it did not matter. She dropped her suitcase and ran. Behind them, the lamplight spilled across the path, warm and golden.",
], [
 dict(d="2a",k="mc",m=1,q="In paragraph 1, what does the word \u201cskittered\u201d suggest the newspaper did?",opts=["Scurried along","Floated slowly","Dropped straight down","Stayed still"],a="A"),
 dict(d="2b",k="short",m=1,q="What was inside Nadia\u2019s suitcase?",a="A silver locket (a birthday present for her grandmother).",g="Accept locket / birthday present."),
 dict(d="2b",k="short",m=1,q="How long had Nadia spent saving for the present?",a="Three months.",g="Accept 3 months."),
 dict(d="2d",k="short",m=1,q="How can you tell that Nadia felt nervous at the start of the story? Give one piece of evidence from the text.",a="She checked her watch three times / her words seemed to have deserted her / she tugged her coat tighter / her voice was barely a whisper.",g="Accept any one relevant quotation or clear reference."),
 dict(d="2g",k="short",m=1,q="The bus \u201cwheezed to a halt\u201d. What does the word \u201cwheezed\u201d suggest about the bus?",a="That it was old / tired / struggling.",g="Accept any answer suggesting age, effort or tiredness."),
 dict(d="2c",k="mc",m=1,q="Which sentence best sums up paragraph 2?",opts=["Nadia is cold and wants to go home.","Nadia has lost her suitcase.","Nadia has a special present and is worried about what to say.","Nadia cannot remember her grandmother\u2019s name."],a="C"),
 dict(d="2d",k="short",m=2,q="Do you think Nadia\u2019s grandmother knew Nadia was coming? Explain your answer using the text.",a="No, it is a surprise: she was \u201cat home revising\u201d as far as her grandmother knew / Nadia says \u201cshe thinks I\u2019m at home revising\u201d.",g="1 mark for \u201cno / it is a surprise\u201d. 1 mark for supporting evidence from paragraph 5 or 6. Max 2."),
 dict(d="2d",k="short",m=1,q="The driver \u201cpeered at her over his glasses\u201d. What might he be thinking?",a="He is surprised / curious to see a young girl alone so late at night.",g="Accept any sensible inference about surprise, concern or curiosity."),
 dict(d="2d",k="short",m=2,q="The woman says, \u201cyou\u2019re in for a treat, love, and so is she.\u201d Explain what she means.",a="Nadia will enjoy the visit / the surprise, and her grandmother will be delighted to see her.",g="1 mark for a treat for Nadia (enjoying the visit / giving the present). 1 mark for a treat for the grandmother (surprise / delight)."),
 dict(d="2g",k="short",m=2,q="The cottage has \u201ca single lamp glowing in its window like a beacon\u201d. What impression does this give of the cottage? Explain your answer.",a="It seems welcoming / a safe place to head for, because a beacon guides people and the lamp stands out in the dark night.",g="1 mark for a suitable impression (welcoming, warm, guiding, safe). 1 mark for explaining with reference to a beacon guiding people or the lamp shining in the dark."),
 dict(d="2d",k="short",m=2,q="Nadia \u201chesitated at the gate\u201d. Give two reasons why she felt unsure.",a="Her grandmother might already be asleep; her grandmother might be cross at being disturbed so late.",g="1 mark for each reason. Max 2."),
 dict(d="2d",k="short",m=2,q="\u201cAll the words Nadia had rehearsed so carefully evaporated once more, but this time it did not matter.\u201d Why did it not matter this time?",a="Her grandmother was so pleased/emotional to see her that no speech was needed; Nadia was happy and simply ran to her.",g="1 mark for the idea that words were not needed / the meeting was more important. 1 mark for a supporting detail (she dropped her case and ran; grandmother whispered \u201cIs that really you?\u201d)."),
 dict(d="2e",k="short",m=2,q="What do you think will happen next? Give a prediction and a reason from the story.",a="Nadia and her grandmother will hug and Nadia will give her the locket, because she has saved for it for months and has come a long way to surprise her.",g="1 mark for a sensible prediction. 1 mark for a reason based on the text."),
 dict(d="2d",k="mc",m=1,q="Which two words best describe Nadia?",opts=["Careless and rude","Bored and lazy","Bossy and loud","Determined and caring"],a="D"),
])
