from tests_src import T, Q2, TF

# ---------------------------------------------------------------- LEVEL 20

T(20, "20-1", "The Last Two Minutes", "Narrative", [
"Zainab pulled on her goalkeeper gloves and tapped them together. It was the last game of the season, and the Riverside Rovers were playing Oakfield. The score was two goals each. There were only two minutes left on the clock.",
"“Stay calm, Zainab,” called her coach, Mr Bell. “You can do this.” Zainab nodded, but her tummy felt as if it was full of butterflies.",
"Suddenly, an Oakfield player raced down the pitch with the ball at her feet. She was fast, and the Rovers’ defenders could not catch her. Zainab crouched low and stared at the ball. The girl swung her leg back and kicked as hard as she could.",
"Zainab leapt to her left. She stretched out her arms as far as they would go, and the ball smacked into her gloves. She held on tightly, even though it stung her hands. “Well saved!” shouted the crowd.",
"Zainab jumped to her feet and threw the ball out to Kofi, who was waiting near the halfway line. Kofi dribbled past one player, then another. He looked up and saw Priya running towards the goal all on her own. He passed the ball to her at just the right moment.",
"Priya did not stop to think. She kicked the ball into the corner of the net, and the goalkeeper could only watch it fly past. The Rovers had scored! A moment later, the referee blew her whistle three times. The match was over.",
"The team cheered and hugged one another. Mr Bell shook Zainab’s hand. “That save won us the game,” he said, smiling. Zainab looked down at her sore fingers and grinned. She did not mind the sting one little bit.",
], [
 dict(d="2b",k="short",m=1,q="What was the score at the start of the story?",a="Two goals each / 2-2.",g="Accept 2-2, two all or two goals each."),
 dict(d="2b",k="mc",m=1,q="What is Zainab’s job in the team?",opts=["Referee","Goalkeeper","Coach","Defender"],a="B"),
 dict(d="2a",k="find",m=1,q="Find and copy one word from paragraph 3 that tells you the Oakfield player ran quickly.",a="raced",g="Accept “raced” or “fast”."),
 dict(d="2d",k="short",m=1,q="Zainab’s tummy “felt as if it was full of butterflies”. How was she feeling?",a="Nervous / worried.",g="Accept nervous, worried, anxious or scared. Do not accept “hungry”."),
 dict(d="2c",k="order",m=1,q="Number the events from 1 to 4 to show the order they happened in.",items=["Priya scored a goal.","Zainab saved the shot.","Kofi dribbled past two players.","The Oakfield player kicked the ball hard."],a=[4,2,3,1],g=Q2),
 dict(d="2b",k="tf",m=1,q="Tick True or False for each sentence.",items=["Mr Bell was the referee.","Kofi passed the ball to Priya.","The Rovers lost the match."],a=["F","T","F"],g=TF),
 dict(d="2d",k="short",m=1,q="How do you know the ball was kicked very hard? Give one clue.",a="It smacked into her gloves / it stung her hands.",g="Accept either clue."),
 dict(d="2a",k="mc",m=1,q="In paragraph 4, what does the word “leapt” mean?",opts=["Walked slowly","Jumped","Fell over","Turned round"],a="B"),
 dict(d="2d",k="short",m=1,q="Why did Mr Bell say, “That save won us the game”?",a="Because if Zainab had not stopped the ball, Oakfield would have scored / the Rovers could not have scored their winning goal.",g="Accept any answer that shows the save stopped Oakfield going ahead and gave the Rovers the chance to win."),
 dict(d="2g",k="short",m=1,q="The writer says the ball “smacked” into Zainab’s gloves. Why is “smacked” a good word to use?",a="It sounds loud and hard, so we can hear how fast the ball was.",g="Accept any answer about the noise, force or speed of the ball."),
 dict(d="2d",k="short",m=1,q="At the end, Zainab “did not mind the sting one little bit”. Why not?",a="She was so happy that her team had won / she was proud of her save.",g="Accept any answer about being happy, proud or pleased with the win."),
])

T(20, "20-2", "Ladybirds in the Garden", "Information Report", [
"Ladybirds are small, round beetles that you can often find in gardens. There are more than forty kinds of ladybird in Britain. The best-known one is the seven-spot ladybird, which has a shiny red back with seven black spots.",
"A ladybird’s bright colours are a warning. Birds that might want to eat a ladybird learn to stay away, because it tastes horrible.",
"Ladybirds are a gardener’s friend. They eat tiny green insects called aphids, which chew the leaves and stems of garden plants. One ladybird can eat as many as fifty aphids in a single day. This helps roses, beans and other plants to grow well without any sprays.",
"A ladybird begins life as an egg. The female lays her eggs in small groups on the underside of a leaf, close to a lot of aphids. When the eggs hatch, the young ladybirds look nothing like their parents. They are long and grey, with orange marks, and they have six legs. These young ones are called larvae, and they are very hungry.",
"After a few weeks, each larva fixes itself to a leaf and turns into a pupa. Inside the pupa, its body slowly changes. About a week later, a new ladybird pushes its way out. At first, it is pale yellow with no spots at all. Its spots and its red colour appear after a few hours.",
"In autumn, ladybirds look for somewhere safe and dry to spend the winter. You might find a group of them tucked away in a crack in a wall, under a piece of bark or inside a dry plant stem. They sleep there until the weather turns warm again in spring.",
"If you want ladybirds to visit your garden, you can help them. Leave a few weeds and some long grass in a corner, and do not use sprays that kill insects.",
], [
 dict(d="2b",k="short",m=1,q="How many spots does a seven-spot ladybird have?",a="Seven.",g="Accept 7."),
 dict(d="2b",k="mc",m=1,q="What do ladybirds eat?",opts=["Leaves","Aphids","Seeds","Flowers"],a="B"),
 dict(d="2a",k="mc",m=1,q="In paragraph 3, what does the word “stems” mean?",opts=["The roots of a plant","The petals of a flower","The long parts that hold up a plant","Tiny insects"],a="C"),
 dict(d="2d",k="short",m=1,q="Why do birds usually leave ladybirds alone?",a="Ladybirds taste horrible and their bright colours warn birds.",g="Accept either: they taste horrible / the bright colours are a warning."),
 dict(d="2c",k="order",m=1,q="Number the stages from 1 to 4 to show how a ladybird grows.",items=["A pupa forms on a leaf.","A grey larva hatches from an egg.","A pale yellow ladybird comes out.","The female lays eggs under a leaf."],a=[3,2,4,1],g=Q2),
 dict(d="2b",k="tf",m=1,q="Tick True or False for each sentence.",items=["Ladybirds lay their eggs on the underside of leaves.","Newly hatched ladybirds look like their parents.","Ladybirds spend the winter in cracks or under bark."],a=["T","F","T"],g=TF),
 dict(d="2d",k="short",m=1,q="Why does the female ladybird lay her eggs close to lots of aphids?",a="So the young ladybirds have plenty of food when they hatch.",g="Accept any answer that links the aphids to food for the larvae. Do not accept “because aphids are green”."),
 dict(d="2a",k="find",m=1,q="Find and copy one word from paragraph 4 that tells you the young ladybirds want a lot of food.",a="hungry",g="Accept “hungry” only."),
 dict(d="2d",k="short",m=1,q="The text says ladybirds are “a gardener’s friend”. Why?",a="They eat the aphids that harm garden plants.",g="Accept any answer about eating aphids or protecting plants."),
 dict(d="2c",k="mc",m=1,q="Which of these is the best heading for paragraph 7?",opts=["How to spot a ladybird","How to make ladybirds welcome","Why ladybirds have spots","What ladybirds eat"],a="B"),
 dict(d="2d",k="short",m=1,q="Why might a gardener who does not want to use sprays be pleased to see a lot of ladybirds?",a="The ladybirds eat the aphids, so the plants stay healthy without sprays.",g="Accept any answer that links ladybirds eating aphids to healthy plants without sprays."),
])

T(20, "20-3", "Grandad's Shell Box", "Narrative", [
"Every summer, Kavi visited his grandad by the sea. Grandad had a wooden box that sat on the shelf in his front room, and it was full of shells. Kavi loved that box more than anything.",
"“Where did they all come from?” Kavi asked one evening, as he lifted out a spiral shell that was as pale as cream.",
"“From beaches all over the world,” said Grandad. “I found that one in Portugal. And this striped one came from a beach in Kenya. Your gran and I collected them on our travels.” Grandad ran a finger along each shell as if it were made of glass.",
"“I want to start a collection,” said Kavi. “Will you help me?” Grandad chuckled. “There’s no better place to start than right outside the door.”",
"The next morning, they took two buckets and walked down to the beach. The tide had gone out, and the sand was wet and shiny. Kavi bent over and soon found a tiny pink shell, then a flat white one, then a curly grey one. Grandad showed him how to pick out the whole shells and leave the broken ones.",
"By lunchtime, Kavi’s bucket was heavy. Back at the cottage, he washed each shell in warm water and laid them out on a towel to dry. Grandad gave him a small cardboard box with sections inside, like an egg carton.",
"That evening, Kavi wrote a label for every shell. He wrote where it was found and the date. His handwriting was rather wobbly, but he did his best. Then he put the box on the shelf, right next to Grandad’s wooden one.",
"“You know,” said Grandad quietly, “that is the best-looking shelf in the whole house.” Kavi smiled all the way to bedtime.",
], [
 dict(d="2b",k="short",m=1,q="Where did Grandad keep his box of shells?",a="On a shelf in his front room.",g="Accept on the shelf / in the front room."),
 dict(d="2b",k="mc",m=1,q="Which country did the striped shell come from?",opts=["Portugal","India","Kenya","England"],a="C"),
 dict(d="2a",k="find",m=1,q="Find and copy one word from paragraph 4 that tells you Grandad laughed quietly.",a="chuckled",g="Accept “chuckled” only (it is in paragraph 4)."),
 dict(d="2d",k="short",m=1,q="Grandad ran his finger along each shell “as if it were made of glass”. What does this tell you about how he felt about his shells?",a="He treated them with great care; they were precious to him.",g="Accept any answer about being careful, gentle or valuing the shells."),
 dict(d="2c",k="order",m=1,q="Number the events from 1 to 4 to show the order they happened in.",items=["Kavi wrote labels for his shells.","Kavi and Grandad went to the beach.","Kavi washed the shells.","Kavi asked about Grandad’s shells."],a=[4,2,3,1],g=Q2),
 dict(d="2b",k="tf",m=1,q="Tick True or False for each sentence.",items=["Kavi and Grandad took two buckets to the beach.","The tide was coming in.","Kavi put his shells in a box with sections."],a=["T","F","T"],g=TF),
 dict(d="2d",k="short",m=1,q="Why did Grandad tell Kavi to leave the broken shells on the beach?",a="Only whole shells are good for a collection / broken shells would not look good.",g="Accept any sensible reason about wanting whole, perfect shells."),
 dict(d="2a",k="mc",m=1,q="In paragraph 6, what does the word “sections” mean?",opts=["Colours","Separate parts","Holes","Lids"],a="B"),
 dict(d="2d",k="short",m=1,q="How can you tell Kavi was proud of his collection? Give one clue.",a="He put it next to Grandad’s box / he did his best with the labels / he smiled all the way to bedtime.",g="Accept any one sensible clue from the last two paragraphs."),
 dict(d="2e",k="mc",m=1,q="What do you think Kavi will do when he visits next summer?",opts=["Throw his shells away","Add more shells to his collection","Stay away from the beach","Give his shells to the shop"],a="B"),
 dict(d="2d",k="short",m=1,q="Why did Grandad say Kavi’s shelf was “the best-looking shelf in the whole house”?",a="To make Kavi feel proud / because he was pleased Kavi had started his own collection.",g="Accept any answer about praise, encouragement or being pleased with Kavi."),
])

T(20, "20-4", "How to Make Flatbreads", "Procedural", [
"Flatbreads are soft, warm and very tasty. You can eat them with soup, roll them around a filling or dip them into hummus. They are quick to make, and you do not need to wait for the dough to rise. Ask an adult to help you, because you will be using a hot pan.",
"You will need:",
"• 300 grams of plain flour, plus a little extra for rolling\n• half a teaspoon of salt\n• 150 grams of plain yoghurt\n• two tablespoons of olive oil\n• a rolling pin, a large bowl and a frying pan",
"Method",
"First, wash your hands. Tip the flour and the salt into the bowl and stir them together with a spoon. Next, add the yoghurt and the oil. Mix everything until it starts to come together in one lump.",
"Now use your hands to squeeze and knead the dough for about five minutes. It should feel soft and smooth, and it should not stick to your fingers. If it is too sticky, add a sprinkle of flour. If it is too dry, add a spoonful of yoghurt.",
"Cover the bowl with a clean tea towel and leave the dough for twenty minutes. This makes it easier to roll out.",
"After that, cut the dough into six equal pieces. Roll each piece into a ball. Dust your table with flour and roll each ball into a flat circle about as thick as a coin.",
"Ask your adult to heat the frying pan until it is hot. Cook one flatbread at a time. After about a minute, small bubbles will appear on top. Flip the bread over and cook the other side for a minute too. Stack the cooked flatbreads under a clean tea towel to keep them warm.",
"Serve your flatbreads while they are still warm. They are best eaten on the same day.",
], [
 dict(d="2b",k="short",m=1,q="Why should you ask an adult to help you?",a="You will be using a hot pan.",g="Accept: the pan is hot / to be safe."),
 dict(d="2b",k="mc",m=1,q="How much flour do you need?",opts=["150 grams","200 grams","300 grams","600 grams"],a="C"),
 dict(d="2b",k="find",m=1,q="Find and copy the two words that tell you what you must wash before you start.",a="your hands",g="Accept “hands”. The answer must be from the first paragraph of the method."),
 dict(d="2a",k="mc",m=1,q="In the method, what does the word “knead” mean?",opts=["To cut into pieces","To squeeze and push dough with your hands","To heat in a pan","To pour into a bowl"],a="B"),
 dict(d="2c",k="order",m=1,q="Number the steps from 1 to 4 to show the correct order.",items=["Cook each flatbread in a hot pan.","Leave the dough to rest for twenty minutes.","Mix the flour, salt, yoghurt and oil.","Roll each ball into a flat circle."],a=[4,2,1,3],g=Q2),
 dict(d="2d",k="short",m=1,q="What should you do if the dough is too dry?",a="Add a spoonful of yoghurt.",g="Accept: add some yoghurt. Do not accept “add flour”."),
 dict(d="2d",k="short",m=1,q="How can you tell that the first side of a flatbread is cooked and ready to turn over?",a="Small bubbles appear on top.",g="Accept bubbles."),
 dict(d="2d",k="short",m=1,q="Why do you think the cooked flatbreads are stacked under a tea towel?",a="To keep them warm.",g="Accept: keeps them warm / stops them going cold."),
 dict(d="2a",k="find",m=1,q="Find and copy one word from the method that means “the same size”.",a="equal",g="Accept “equal” only."),
 dict(d="2d",k="short",m=1,q="The text says flatbreads are “quick to make”. Which part of the method shows why they are quick?",a="You do not need to wait for the dough to rise / you only leave the dough for twenty minutes.",g="Accept either idea."),
 dict(d="2g",k="short",m=1,q="Why do you think the writer uses the words “First”, “Next” and “Now” at the start of some sentences?",a="To show the order of the steps.",g="Accept any answer about order, sequence or helping the reader follow the steps."),
])

T(20, "20-5", "The Train to the Sea", "Recount (Fictional)", [
"On Saturday morning, my dad woke me up before the sun was out. “Come on, Mia,” he whispered. “We have a train to catch.” I sat up straight. We were going to the seaside for the very first time.",
"At the station, the platform was full of people with bags and buckets. I held Dad’s hand tightly as the train rattled in. It was long and green, and it let out a loud hiss when it stopped. We climbed aboard and found two seats by the window.",
"The train began to move slowly, then faster and faster. Houses and gardens flashed past. I counted seven horses in one field, and then a tractor, and then a tiny church on a hill. Dad gave me a cheese sandwich, and I ate it while I watched the world zoom by.",
"After an hour, we went through a long tunnel. Everything went dark, and the windows turned into mirrors. I could see my own face looking back at me. I squeezed Dad’s arm, but he only laughed. “Wait for it,” he said.",
"Then we shot out into the light, and there it was. The sea stretched out flat and shining, as far as I could see. It was bluer than my school jumper. White birds circled above it, and their cries sounded like laughing.",
"“Is that really the sea?” I asked. “It’s so big!” Dad nodded and smiled.",
"A few minutes later, the train slowed down and stopped. The doors slid open, and a salty breeze rushed in. I jumped down onto the platform and pulled Dad towards the sand. It had been a long journey, but I did not feel tired at all.",
], [
 dict(d="2b",k="short",m=1,q="What time of day was it when Dad woke Mia?",a="Very early / before the sun was out.",g="Accept early morning or before sunrise."),
 dict(d="2b",k="mc",m=1,q="What did Dad give Mia to eat on the train?",opts=["A cheese sandwich","An apple","A biscuit","Some crisps"],a="A"),
 dict(d="2a",k="find",m=1,q="Find and copy one word from paragraph 2 that tells you the train made a loud sound when it stopped.",a="hiss",g="Accept \u201chiss\u201d only."),
 dict(d="2d",k="short",m=1,q="How do you know this was Mia’s first visit to the seaside?",a="The text says they were going to the seaside for the very first time / she asks “Is that really the sea?”",g="Accept either clue."),
 dict(d="2c",k="order",m=1,q="Number the events from 1 to 4 to show the order they happened in.",items=["The train went through a tunnel.","Mia saw the sea.","Mia and Dad waited on the platform.","The train stopped and the doors opened."],a=[2,3,1,4],g=Q2),
 dict(d="2b",k="tf",m=1,q="Tick True or False for each sentence.",items=["Mia counted seven horses in a field.","The tunnel was bright inside.","Mia was tired at the end of the journey."],a=["T","F","F"],g=TF),
 dict(d="2d",k="short",m=1,q="Why did Mia squeeze Dad’s arm in the tunnel?",a="It was dark and she felt a bit nervous / unsure.",g="Accept any answer linked to the dark or feeling nervous."),
 dict(d="2a",k="mc",m=1,q="In paragraph 5, what does the word “stretched” mean?",opts=["Bent","Spread out","Splashed","Shrank"],a="B"),
 dict(d="2g",k="short",m=1,q="Mia says the sea was “bluer than my school jumper”. Why does she make this comparison?",a="To show how bright and deep the blue was, using something she knows well.",g="Accept any answer about showing how blue the sea was."),
 dict(d="2d",k="short",m=1,q="What tells you Mia was excited at the end of the story?",a="She jumped down and pulled Dad towards the sand / she did not feel tired at all.",g="Accept either clue."),
 dict(d="2d",k="short",m=1,q="Why do you think Dad laughed and said “Wait for it” in the tunnel?",a="He knew the tunnel would end soon and the sea would appear.",g="Accept any answer about a surprise coming or the tunnel ending."),
])

T(20, "20-6", "Diwali, the Festival of Lights", "Information Report", [
"Diwali is a festival that is celebrated by millions of people around the world. It is often called the Festival of Lights. People who are Hindu, Sikh and Jain all celebrate Diwali, although they may do so for different reasons. The festival happens in autumn, usually in October or November.",
"Diwali lasts for five days. The main celebration takes place on the third day, on the night of the new moon. On this night the sky is very dark, so the many lights people put out shine even more brightly.",
"Lamps are a very important part of Diwali. Families light small clay lamps called diyas and place them on windowsills, doorsteps and along garden walls. Some people also hang strings of colourful lights outside their homes. Lighting the lamps is a way of welcoming happiness into the house.",
"Before the festival, people often clean their homes from top to bottom. They also make patterns called rangoli on the floor near the front door. A rangoli can be made with coloured powder, rice or flower petals. The bright shapes and colours are meant to welcome visitors.",
"Food is another big part of Diwali. Families cook special meals and make sweets to share. Popular sweets include laddoos, which are little round balls, and barfi, which is cut into small squares. People give boxes of sweets to their friends and neighbours as gifts.",
"Many people wear new clothes for Diwali. Families visit each other, send cards and give presents. In many places there are also firework displays at night, which fill the sky with colour.",
"Diwali is a time for families and friends to come together. Whether it is lighting a lamp, making a rangoli or sharing a sweet, each part of the festival is about joy and kindness.",
], [
 dict(d="2b",k="short",m=1,q="How many days does Diwali last?",a="Five days.",g="Accept 5."),
 dict(d="2b",k="mc",m=1,q="In which season does Diwali happen?",opts=["Spring","Summer","Winter","Autumn"],a="D"),
 dict(d="2a",k="find",m=1,q="Find and copy the name of the small clay lamps used at Diwali.",a="diyas",g="Accept \u201cdiyas\u201d (or \u201cdiya\u201d)."),
 dict(d="2b",k="tf",m=1,q="Tick True or False for each sentence.",items=["Rangoli patterns are made near the front door.","Laddoos are cut into small squares.","Only Hindu people celebrate Diwali."],a=["T","F","F"],g=TF),
 dict(d="2d",k="short",m=1,q="Why do the lights shine “even more brightly” on the main night?",a="Because the sky is very dark (new moon).",g="Accept any answer about the dark sky or no moon."),
 dict(d="2a",k="mc",m=1,q="In paragraph 4, what does the word “patterns” mean?",opts=["Meals","Designs made of shapes and colours","Clothes","Gifts"],a="B"),
 dict(d="2c",k="mc",m=1,q="Which of these is the best heading for paragraph 5?",opts=["Lamps and lights","Cleaning the home","Food and sweets","Fireworks"],a="C"),
 dict(d="2d",k="short",m=1,q="Why do you think people clean their homes before Diwali?",a="To get the house ready for visitors / to welcome happiness.",g="Accept any sensible reason about getting ready, visitors or a fresh start."),
 dict(d="2d",k="short",m=1,q="How can you tell that sharing is an important part of Diwali? Give one example from the text.",a="People give boxes of sweets to friends and neighbours / cook meals to share / give presents.",g="Accept any one example."),
 dict(d="2c",k="order",m=1,q="Number the parts of the text from 1 to 4 in the order they appear.",items=["Sweets and special meals","Lamps called diyas","How long the festival lasts","Rangoli patterns"],a=[4,2,1,3],g=Q2),
 dict(d="2g",k="short",m=1,q="The writer says Diwali is “about joy and kindness”. Which word tells us that the festival is happy?",a="joy",g="Accept \u201cjoy\u201d."),
])

# ---------------------------------------------------------------- LEVEL 21

T(21, "21-1", "The Bookshop on Chapel Lane", "Narrative", [
"On Saturdays, Ravi helped his aunt in her second-hand bookshop. It was a narrow, crooked little shop, and every wall was piled high with books. Ravi’s job was to dust the shelves and put returned books back in their proper places.",
"One rainy afternoon, an elderly man came in, shaking the drops from his umbrella. “I am looking for a book I loved as a boy,” he said, “but I have forgotten the title.” Ravi’s aunt was busy at the till, so Ravi stepped forward. “I could help you look,” he said.",
"“What do you remember about it?” asked Ravi. The man frowned and stared at the ceiling. “It had a green cover,” he said slowly. “It was about a boy who sailed across the sea in a small boat. And there was a parrot who could talk.”",
"Ravi began to search. He pulled out a green book called Farmer Jack, but the man shook his head. He tried another, about a family of ducks, but that was not right either. The man sighed. “Perhaps it was too long ago,” he said.",
"“Wait,” said Ravi. He remembered a shelf near the window where he had been tidying that morning. He hurried over and ran his finger along the spines. Halfway along, he spotted a faded green cover with a tiny picture of a boat. The title was The Boy and the Blue Parrot.",
"He carried it back to the man, who took it in both hands as though it were made of glass. He opened the first page and read a few lines. Then his face broke into a huge smile. “This is the very one,” he whispered. “I have not seen it for sixty years.”",
"At the door, he turned to Ravi. “Thank you,” he said. “You have a real gift for finding things.”",
"When the door had closed, Ravi’s aunt winked at him. “You may just have a job here when you are older,” she said. Ravi grinned and went back to his dusting, feeling ten feet tall.",
], [
 dict(d="2b",k="short",m=1,q="What was Ravi’s job in the bookshop?",a="To dust the shelves and put returned books back in their places.",g="Accept either part."),
 dict(d="2b",k="mc",m=1,q="What did the man remember about the book?",opts=["It was very long","It had a red cover","It was about a farmer","It had a talking parrot in it"],a="D"),
 dict(d="2a",k="find",m=1,q="Find and copy one word from paragraph 1 that tells you the shop was not wide.",a="narrow",g="Accept \u201cnarrow\u201d only."),
 dict(d="2a",k="mc",m=1,q="In paragraph 3, what does the word “frowned” suggest the man was doing?",opts=["Laughing","Trying hard to remember","Falling asleep","Getting angry"],a="B"),
 dict(d="2c",k="order",m=1,q="Number the events from 1 to 4 to show the order they happened in.",items=["Ravi found a faded green book.","The man said he had forgotten the title.","Ravi’s aunt winked at him.","Ravi showed the man a book about ducks."],a=[3,1,4,2],g=Q2),
 dict(d="2b",k="tf",m=1,q="Tick True or False for each sentence.",items=["The man was carrying an umbrella.","Ravi found the book on a shelf near the window.","The man had read the book last year."],a=["T","T","F"],g=TF),
 dict(d="2d",k="short",m=1,q="Why did Ravi offer to help the man instead of his aunt?",a="His aunt was busy at the till.",g="Accept any answer about his aunt being busy."),
 dict(d="2d",k="short",m=1,q="How can you tell that the book mattered a great deal to the man?",a="He took it in both hands as if it were made of glass / he smiled hugely / he had not seen it for sixty years.",g="Accept any one clue from paragraph 6."),
 dict(d="2g",k="short",m=1,q="Ravi went back to his dusting “feeling ten feet tall”. What does this tell you about how he felt?",a="Proud and happy.",g="Accept proud, pleased, confident or happy. Do not accept “tall” taken literally."),
 dict(d="2d",k="short",m=1,q="What did Ravi’s aunt mean when she said he might have “a job here when you are older”?",a="She thought Ravi was good at the work and might be able to work in the shop one day.",g="Accept any answer that shows she was impressed or praising him."),
 dict(d="2e",k="mc",m=1,q="What do you think Ravi will do the next Saturday?",opts=["Stop going to the shop","Help his aunt in the shop again","Sell the parrot book","Move to another town"],a="B"),
])

T(21, "21-2", "From Bean to Bar", "Explanation", [
"Chocolate comes from the seeds of a tree called the cacao tree. These trees grow only in warm, wet parts of the world, such as West Africa and South America. It takes a great many steps to turn those seeds into the smooth chocolate that we buy in shops.",
"The story begins with the cacao pod. A pod is about the size of a small rugby ball, and it grows straight out of the tree’s trunk and branches. Inside each pod are about forty seeds, called beans, which are covered in a sticky white pulp. Farmers cut the pods open with a large knife and scoop out the beans.",
"Next, the beans are piled up and covered with leaves for several days. During this time, they heat up and begin to change. This step is called fermenting. It is very important, because it is what starts to give the beans their rich, chocolate flavour.",
"After that, the beans are spread out in the sun to dry. Farmers turn them over regularly so that they dry evenly. When they are dry, the beans are packed into sacks and sent by ship to factories all over the world.",
"At the factory, the beans are roasted in large ovens. Roasting makes the flavour stronger and the smell delicious. Then the thin shells are cracked off, and the insides are ground into a thick, dark paste.",
"The paste is not yet sweet. To make the chocolate we like to eat, makers mix in sugar. For milk chocolate, they also add milk. The mixture is then stirred slowly for many hours until it is silky smooth.",
"Finally, the warm liquid chocolate is poured into moulds and left to cool. As it cools, it becomes hard and shiny. The bars are wrapped and packed, and then they are ready to be taken to shops.",
"So the next time you enjoy a piece of chocolate, remember how far it has travelled and how many people helped to make it.",
], [
 dict(d="2b",k="mc",m=1,q="What do cacao trees grow in?",opts=["Cold, dry places","Warm, wet places","Deserts","Mountains"],a="B"),
 dict(d="2b",k="short",m=1,q="About how many beans are inside each pod?",a="About forty.",g="Accept 40."),
 dict(d="2a",k="find",m=1,q="Find and copy the word that names the step when the beans are covered with leaves and heat up.",a="fermenting",g="Accept \u201cfermenting\u201d only."),
 dict(d="2a",k="mc",m=1,q="In paragraph 6, what does the word “silky” suggest about the chocolate?",opts=["Very hot","Smooth and soft","Sticky","Crunchy"],a="B"),
 dict(d="2c",k="order",m=1,q="Number the steps from 1 to 4 to show how chocolate is made.",items=["The beans are roasted in a factory.","The beans are dried in the sun.","The liquid chocolate is poured into moulds.","Farmers scoop the beans out of the pods."],a=[3,2,4,1],g=Q2),
 dict(d="2b",k="tf",m=1,q="Tick True or False for each sentence.",items=["Cacao pods grow on the trunk and branches of the tree.","The beans are sent to factories by ship.","Roasting makes the beans taste weaker."],a=["T","T","F"],g=TF),
 dict(d="2d",k="short",m=1,q="Why do farmers turn the beans over while they dry in the sun?",a="So that they dry evenly.",g="Accept: so all the beans dry properly / evenly."),
 dict(d="2d",k="short",m=1,q="The paste is “not yet sweet”. What is added to make it sweet?",a="Sugar.",g="Accept sugar."),
 dict(d="2d",k="short",m=1,q="Why do you think the chocolate becomes hard only after it is poured into moulds?",a="Because it cools down and hardens there.",g="Accept any answer linked to cooling."),
 dict(d="2c",k="mc",m=1,q="Which sentence best sums up the whole text?",opts=["Farmers grow cacao trees in Britain.","Chocolate is only made from milk and sugar.","Chocolate is made by turning cacao beans through many careful steps.","Rugby balls are made from cacao pods."],a="C"),
 dict(d="2g",k="short",m=1,q="The last paragraph says to “remember how far it has travelled”. What does the writer want the reader to think about?",a="How chocolate comes from far away and takes many steps and people to make.",g="Accept any answer about the long journey, the many steps or the many people involved."),
])

T(21, "21-3", "Snail Race", "Narrative", [
"Every year in Aisha’s school, the Year Threes held a snail race. Aisha had been looking forward to it for weeks. She had found her snail under a flowerpot in the garden, and she had named him Turbo.",
"On the morning of the race, Mrs Kelly drew a large circle on the playground with chalk. The snails were to be placed in the middle, and the first snail to reach the edge would be the winner. Aisha set Turbo down carefully and crossed her fingers.",
"“Ready, steady, go!” called Mrs Kelly. For a long moment, nothing happened. Then Turbo pulled his head into his shell and stayed exactly where he was. Aisha groaned. The other snails were slowly creeping outwards, leaving shiny silver trails behind them.",
"“Oh, Turbo,” Aisha muttered. “Please move.” Her friend Callum leaned over her shoulder. “Mine is nearly at the edge,” he said proudly. “He’s called Lightning.” Aisha sighed. It seemed that Turbo had not been the best choice.",
"Then something odd happened. The playground had been warming up in the sun all morning, and Turbo’s head slowly reappeared. He stretched out his long, soft body and began to glide across the ground. He was not fast, but he kept going without stopping.",
"Meanwhile, Callum’s snail had wandered off in the wrong direction and was heading back towards the middle. Other snails had stopped to rest, and one had even begun to climb up a boy’s shoe.",
"Turbo kept moving steadily. Inch by inch, he crept towards the chalk line, and Aisha held her breath. At last, his front end slid across it. “We have a winner!” cried Mrs Kelly. The whole class cheered.",
"Aisha scooped up her snail and held him in her palm. “You were just waiting for the right moment,” she said, laughing. Turbo stayed in his shell, looking quite pleased with himself. Then Aisha carried him carefully back to the flowerpot where she had found him.",
], [
 dict(d="2b",k="short",m=1,q="Where did Aisha find her snail?",a="Under a flowerpot in the garden.",g="Accept under a flowerpot."),
 dict(d="2b",k="mc",m=1,q="How did Mrs Kelly mark out the race?",opts=["With a rope","With a chalk circle","With cones","With a ruler"],a="B"),
 dict(d="2a",k="find",m=1,q="Find and copy one word from paragraph 3 that tells you what the snails left behind on the ground.",a="trails",g="Accept \u201ctrails\u201d or \u201cshiny silver trails\u201d."),
 dict(d="2a",k="mc",m=1,q="In paragraph 5, what does the word “glide” mean?",opts=["Move smoothly","Jump high","Roll over","Run fast"],a="A"),
 dict(d="2c",k="order",m=1,q="Number the events from 1 to 4 to show the order they happened in.",items=["Turbo crossed the chalk line.","Mrs Kelly shouted “Ready, steady, go!”","Turbo pulled his head into his shell.","Turbo began to glide across the ground."],a=[4,1,2,3],g=Q2),
 dict(d="2b",k="tf",m=1,q="Tick True or False for each sentence.",items=["Callum’s snail was called Lightning.","One snail climbed up a boy’s shoe.","Aisha kept Turbo as a pet at home."],a=["T","T","F"],g=TF),
 dict(d="2d",k="short",m=1,q="Why do you think Turbo began to move after the playground had warmed up in the sun?",a="Snails move more when they are warm / the warmth woke him up.",g="Accept any answer linked to warmth."),
 dict(d="2d",k="short",m=1,q="Why did Aisha groan when Turbo pulled his head into his shell?",a="She thought he would lose the race / she was disappointed.",g="Accept any answer about disappointment or worry that he would lose."),
 dict(d="2d",k="short",m=1,q="Why did Callum’s snail not win the race, even though it was nearly at the edge?",a="It wandered off in the wrong direction and headed back to the middle.",g="Accept any answer about going the wrong way."),
 dict(d="2g",k="short",m=1,q="The writer says Turbo looked “quite pleased with himself”. What does this make you imagine?",a="Turbo was proud, as if he knew he had won.",g="Accept any answer about the snail seeming proud or satisfied."),
 dict(d="2e",k="short",m=1,q="What lesson could Aisha learn from the race? Use the story to explain.",a="Slow and steady can win / do not give up too soon.",g="Accept any sensible lesson supported by Turbo’s steady progress."),
])

T(21, "21-4", "The Great Swallow Journey", "Information Report", [
"Every spring, swallows arrive in Britain from a long way away. These small, graceful birds have shiny blue backs, red throats and long, forked tails. Each swallow weighs less than a slice of bread. Yet, each year, it makes one of the longest journeys of any small bird.",
"Swallows spend the winter in southern Africa, where it is warm and there are plenty of insects to eat. When spring comes, they set off north. The journey is more than five thousand miles long, and it takes several weeks. On the way, the birds cross the sea, the Sahara Desert and the mountains of Europe.",
"Swallows do almost everything while flying. They catch flies and other insects in mid-air, and they can even drink by skimming low over a pond and scooping up water in their beaks. This means they do not need to land very often, which is useful on such a long trip.",
"Amazingly, a swallow often returns to the same place that it left the year before. If it can, it will use the same nest. Swallows build their nests from small balls of mud mixed with grass. They stick them inside barns and sheds, or under the roofs of buildings. The nest is shaped like a little cup.",
"A female swallow lays between four and five eggs. Both parents take turns feeding the chicks, and they may make hundreds of trips each day to bring insects to the nest. After about three weeks, the young birds are ready to fly.",
"By late summer, swallows gather in large groups. You may see them sitting in a row on a wire, chattering to one another. When autumn arrives, the insects become harder to find. It is then that the swallows leave to make the long journey back to Africa.",
"No one knows for certain how swallows find their way. Scientists think they may use the sun, the stars and even the shape of the land below them. Whatever their secret, swallows show that even a tiny bird can travel a very long way.",
], [
 dict(d="2b",k="short",m=1,q="Where do swallows spend the winter?",a="In southern Africa.",g="Accept Africa."),
 dict(d="2b",k="mc",m=1,q="How long is the swallows’ journey north?",opts=["More than five hundred miles","More than five thousand miles","About fifty miles","More than fifty thousand miles"],a="B"),
 dict(d="2a",k="find",m=1,q="Find and copy one word from paragraph 1 that means “elegant”.",a="graceful",g="Accept \u201cgraceful\u201d only."),
 dict(d="2a",k="mc",m=1,q="In paragraph 3, what does the word “skimming” mean?",opts=["Diving deep","Sitting still","Moving quickly just above a surface","Hiding"],a="C"),
 dict(d="2c",k="order",m=1,q="Number the stages from 1 to 4 to show a swallow’s year.",items=["The chicks learn to fly.","The swallows fly back to Africa.","The swallows arrive in Britain in spring.","The swallows gather on wires."],a=[2,4,1,3],g=Q2),
 dict(d="2b",k="tf",m=1,q="Tick True or False for each sentence.",items=["Swallows make their nests from mud and grass.","Only the female swallow feeds the chicks.","Swallows often use the same nest each year."],a=["T","F","T"],g=TF),
 dict(d="2d",k="short",m=1,q="Why do swallows leave Britain in autumn?",a="The insects become harder to find.",g="Accept: less food / fewer insects."),
 dict(d="2d",k="short",m=1,q="Why is it useful that swallows can drink while flying?",a="They do not have to land very often on their long journey.",g="Accept any answer about saving time or not needing to stop."),
 dict(d="2d",k="short",m=1,q="The writer says a swallow “weighs less than a slice of bread”. What is the writer showing the reader?",a="How small and light the bird is, which makes its journey more amazing.",g="Accept: it is very small / light."),
 dict(d="2c",k="mc",m=1,q="Which sentence best sums up paragraph 4?",opts=["Swallows never build nests.","Swallows like to return to the same place and build cup-shaped mud nests.","Barns are dangerous for swallows.","Swallows lay eggs in the sea."],a="B"),
 dict(d="2g",k="short",m=1,q="The writer ends by saying that “even a tiny bird can travel a very long way”. Why is the word “even” used?",a="To show that it is surprising for such a small bird.",g="Accept any answer about surprise or contrast between size and distance."),
])

T(21, "21-5", "Lantern Night", "Description", [
"It was the evening of the Lantern Festival, and the whole town had come out to the park. The sky was turning from pink to deep blue, and the air was crisp and cool. Nobody wanted to go home.",
"Along the path, hundreds of paper lanterns hung from the branches of the trees. Some were round and red, like tiny glowing suns. Others were shaped like fish, with orange scales and long tails that swayed in the breeze. A lantern in the shape of a dragon curled around a lamppost, and its eyes flickered gold.",
"Children ran between the trees, holding their own lanterns on sticks. Mei carried a white rabbit that she had made at school with her friends. Its ears were made from folded paper, and a small candle glowed inside its round body. She held it high above her head so everyone could see.",
"The smells drifted across the grass. There were sweet rice balls from a little stall, and roasted chestnuts that crackled in a paper bag. Someone was selling hot orange juice in tiny cups. A man beside the fountain played a gentle tune on a wooden flute.",
"At eight o’clock, a drum began to beat. Boom, boom, boom. The crowd turned towards the lake, where a line of floating lanterns was being lowered on to the water. They bobbed gently, and their reflections wobbled and danced.",
"Mei’s grandmother came to stand beside her. “Isn’t it lovely?” she said softly. Mei nodded and squeezed her hand. She thought the lake looked as though someone had scattered stars across it.",
"Slowly, the lanterns drifted apart. The drum grew quieter and then stopped altogether. For a moment, the whole park was silent. Then the crowd began to clap, and the sound rolled across the water like a wave.",
"Mei walked home slowly, her rabbit lantern still glowing in her hand. She knew that she would remember that night for a very long time.",
], [
 dict(d="2b",k="short",m=1,q="What was the name of the festival?",a="The Lantern Festival.",g="Accept Lantern Festival."),
 dict(d="2b",k="mc",m=1,q="What animal was Mei’s lantern?",opts=["A dragon","A fish","A rabbit","A sun"],a="C"),
 dict(d="2a",k="find",m=1,q="Find and copy one word from paragraph 2 that tells you the fish lanterns moved gently from side to side.",a="swayed",g="Accept \u201cswayed\u201d only."),
 dict(d="2a",k="mc",m=1,q="In paragraph 1, what does the word “crisp” suggest about the air?",opts=["Warm and damp","Fresh and cool","Smoky","Thick and heavy"],a="B"),
 dict(d="2c",k="order",m=1,q="Number the events from 1 to 4 to show the order they happened in.",items=["The crowd clapped.","A drum began to beat.","Floating lanterns were lowered on to the lake.","Mei walked home."],a=[3,1,2,4],g=Q2),
 dict(d="2b",k="tf",m=1,q="Tick True or False for each sentence.",items=["Mei made her lantern at school.","A man played a flute beside the fountain.","Mei’s grandfather stood beside her at the lake."],a=["T","T","F"],g=TF),
 dict(d="2d",k="short",m=1,q="How can you tell that people enjoyed the festival? Give one clue.",a="Nobody wanted to go home / the crowd clapped / Mei said it was lovely.",g="Accept any one sensible clue."),
 dict(d="2d",k="short",m=1,q="Why do you think Mei held her lantern high above her head?",a="So that everyone could see it / she was proud of it.",g="Accept: to show it off / so people could see it."),
 dict(d="2g",k="short",m=1,q="Mei thought the lake looked “as though someone had scattered stars across it”. Why is this a good way to describe the floating lanterns?",a="The small lights on the dark water look like stars in the sky.",g="Accept any answer about small glowing lights looking like stars."),
 dict(d="2d",k="short",m=1,q="What does the word “wobbled” in paragraph 5 tell you about the reflections on the lake?",a="They were moving/shaking because the water was moving.",g="Accept: they were not still / they shook gently."),
 dict(d="2e",k="short",m=1,q="Why do you think Mei knew she would remember that night for a very long time?",a="It was beautiful and special / she made her own lantern and enjoyed it with her grandmother.",g="Accept any sensible reason about a special or enjoyable evening."),
])

T(21, "21-6", "Should We Walk to School?", "Exposition", [
"Every morning, the roads outside our school are full of cars. Parents queue at the gates, engines humming, while children hurry in through the traffic. I believe that many more of us should walk to school, and there are three good reasons why.",
"First, walking is good for our health. Children need to be active every day, and a walk to school is an easy way to do it. Even a short walk gets our hearts pumping and our legs moving. When we arrive, we are awake and ready to learn. Pupils who have been sitting in a car often feel sleepy and slow.",
"Second, walking is better for the environment. Cars burn petrol, and this makes fumes that dirty the air. The air near a busy school gate can be unpleasant to breathe. If fewer families came by car, the air would be cleaner for everyone, and the road outside would be safer too.",
"Finally, walking is enjoyable. On foot, we can chat with friends and notice things that we would miss from a car window, such as a squirrel darting up a tree or the first flowers of spring. Some of my best conversations have happened on the way to school.",
"Some people argue that walking takes too long, or that the weather is often bad. However, many families live close enough to walk in less than fifteen minutes. And, as the saying goes, there is no such thing as bad weather, only the wrong clothes. A good coat and a pair of boots solve the problem.",
"Of course, not every family can walk. Some children live too far away, and some need a car for other reasons. But those who can walk should try it.",
"In conclusion, walking to school is healthy, kind to the planet and fun. If we all tried it just one day a week, our school would be a happier, cleaner and safer place.",
], [
 dict(d="2b",k="short",m=1,q="What is the writer trying to persuade the reader to do?",a="Walk to school.",g="Accept: walk to school more often."),
 dict(d="2b",k="mc",m=1,q="How many good reasons does the writer give at the start?",opts=["Two","Four","Five","Three"],a="D"),
 dict(d="2a",k="find",m=1,q="Find and copy one word from paragraph 3 that means “gases or smoke from engines”.",a="fumes",g="Accept \u201cfumes\u201d only."),
 dict(d="2a",k="mc",m=1,q="In paragraph 1, what does the word “queue” mean?",opts=["Wait in a line","Park badly","Race quickly","Shout loudly"],a="A"),
 dict(d="2c",k="order",m=1,q="Number the points from 1 to 4 to show the order the writer makes them.",items=["Walking is fun.","There are too many cars at the school gate.","Walking is better for the environment.","Walking is good for our health."],a=[4,1,3,2],g=Q2),
 dict(d="2b",k="tf",m=1,q="Tick True or False for each sentence.",items=["The writer thinks walking is enjoyable.","The writer says every family can walk.","Some families live less than fifteen minutes away."],a=["T","F","T"],g=TF),
 dict(d="2d",k="short",m=1,q="Why does the writer say children who walk are “awake and ready to learn”?",a="Walking wakes them up and gets them moving, unlike sitting in a car.",g="Accept any answer about exercise or being alert."),
 dict(d="2d",k="short",m=1,q="What does the writer suggest is the answer to bad weather?",a="Wear a good coat and boots.",g="Accept: the right clothes."),
 dict(d="2d",k="short",m=1,q="Why does the writer include paragraph 6, which says that not every family can walk?",a="To show that the writer is fair and understands that some families cannot walk.",g="Accept any answer about being fair, realistic or understanding other views."),
 dict(d="2g",k="short",m=1,q="The writer says walking gets “our hearts pumping”. Why is this a good way to make the reader think about exercise?",a="It makes us picture our bodies working and becoming stronger.",g="Accept any sensible answer about showing how walking works the body."),
 dict(d="2c",k="mc",m=1,q="Which sentence best sums up the whole text?",opts=["Cars are always bad.","Children should never go to school by car in the rain.","More children should walk to school because it is healthy, kind to the planet and fun.","Walking takes too long."],a="C"),
])
