from tests_src import T, Q2, TF

# ---------------------------------------------------------------- LEVEL 22
T(22, "22-1", "The New Girl", "Narrative", [
"Maya had sat at the same table since Reception, but on Monday morning there was a new face beside the window. The girl had short black hair and a bright yellow backpack, and she was staring hard at her shoes.",
"“This is Amara,” said Mr Hall. “She has just moved here from Nigeria. Who would like to look after her today?” No hands went up. Everyone was too shy.",
"Maya felt her tummy flip. Then she remembered her first day at gym club, when nobody had spoken to her at all. Slowly, she put up her hand.",
"At break, Maya showed Amara where the water fountain was and which toilets never had a queue. Amara nodded but said very little. At lunch, she only picked at her sandwich.",
"“Don’t you like it?” asked Maya.",
"“It is fine,” said Amara quietly. “I just miss my old school. Everybody knew my name there.”",
"Maya thought hard. Then she had an idea. She pulled a felt-tip pen from her pocket and grabbed a paper napkin. “Let’s play a game,” she said. “I will draw a shape, and you add to it until it turns into an animal.” She drew a wobbly circle.",
"Amara took the pen. She gave the circle two long ears and a fluffy tail, and then she giggled. “It’s a rabbit!” she said.",
"Next, they drew a giraffe, a snail and a very strange fish with legs. By the time the bell rang, the napkin was covered in scribbles, and both girls were laughing so loudly that the dinner lady turned round to look.",
"On the way back to class, Amara stopped. “Thank you, Maya,” she said. “You are the first person who has asked me to play.”",
"Maya smiled. “Tomorrow, you can choose the game,” she said. “And I will bring more paper.”",
"Amara was not staring at her shoes any more. She was holding her head up, and her yellow backpack bounced happily as she walked.",
], [
 dict(d="2a",k="find",m=1,q="Find and copy one word that tells you how the children in the class felt when Mr Hall asked for help.",a="shy",g="Accept “shy” only."),
 dict(d="2b",k="short",m=1,q="Where had Amara just moved from?",a="Nigeria.",g="Accept Nigeria."),
 dict(d="2b",k="mc",m=1,q="What did Maya remember that made her put up her hand?",opts=["Her first day at gym club","Her old teacher","A game she had played with her brother","A time she got lost at break"],a="A"),
 dict(d="2c",k="order",m=1,q="Number the events from 1 to 4 to show the order they happened in the story.",items=["Amara said thank you.","Mr Hall asked for someone to look after Amara.","Maya drew a wobbly circle.","Maya showed Amara the water fountain."],a=[4,1,3,2],g=Q2),
 dict(d="2d",k="short",m=1,q="Why do you think Amara only picked at her sandwich?",a="She was sad because she missed her old school.",g="Accept any answer that links to sadness, missing her old school or feeling lonely. Do not accept “she did not like it”."),
 dict(d="2d",k="short",m=1,q="How do you know that Maya understood how Amara was feeling?",a="Maya remembered how she felt on her first day at gym club when nobody spoke to her.",g="Accept any answer that mentions Maya remembering her own first day, or a time she felt left out."),
 dict(d="2a",k="mc",m=1,q="In the story, what does the word “wobbly” mean?",opts=["Very large","Not steady","Perfectly round","Bright"],a="B"),
 dict(d="2b",k="tf",m=1,q="Tick True or False for each sentence.",items=["Amara added ears and a tail to the circle.","Maya was new to the school.","The dinner lady laughed loudly.","Maya said she would bring more paper."],a=["T","F","F","T"],g=TF),
 dict(d="2b",k="short",m=1,q="What was the first animal that Maya and Amara made from the circle?",a="A rabbit.",g="Accept rabbit."),
 dict(d="2d",k="short",m=1,q="At the end, Amara was “holding her head up”. What does this tell you about how she was feeling?",a="She felt happier / more confident.",g="Accept happy, cheerful, proud, confident, better."),
 dict(d="2g",k="short",m=1,q="The author says Amara’s backpack “bounced happily”. What does this show about the way Amara was walking?",a="She was walking in a bouncy, cheerful way.",g="Accept any answer showing she was walking lightly or joyfully."),
 dict(d="2e",k="short",m=1,q="What do you think Amara and Maya will do tomorrow?",a="Play a game that Amara chooses.",g="Accept any answer about playing together, drawing again or Amara choosing a game."),
])

T(22, "22-2", "Life in a Pond", "Information Report", [
"A pond is a small area of still water, often with plants growing around its edges. From the bank, a pond can look quiet, but it is really a busy habitat. A habitat is the place where a plant or an animal lives and finds everything it needs. Hundreds of small creatures can live in one garden pond.",
"A pond has different layers, and each one suits different animals. On the surface, pond skaters glide across the water without sinking. Their bodies are very light, and their long, thin legs spread their weight out, so they do not break the surface.",
"Below the surface, in the open water, fish and tadpoles swim about. Tadpoles hatch from the jelly-like eggs that frogs lay in spring. They feed on tiny green plants, and slowly they grow back legs and then front legs.",
"At the bottom of the pond, there is thick mud. Snails, worms and dragonfly nymphs live here. A nymph is a young dragonfly that has no wings. It hides in the mud and snaps up tadpoles and other small creatures as they pass by. When it is fully grown, the nymph climbs up the stem of a plant. Its skin splits open, and the adult dragonfly crawls out and flies away.",
"Plants are important in a pond too. Water lilies have flat leaves that float on the top. These give shade and hiding places for the animals underneath. Plants that grow under the water make oxygen, which many pond animals need to breathe.",
"Some animals visit the pond but do not live there. Birds come to drink and to wash their feathers. A heron may stand very still at the edge for a long time, waiting to catch a fish.",
"If you dig a pond in your garden, you can help wildlife by making one side slope gently. Then animals that fall in can climb out safely. Before long, the first visitors will arrive.",
], [
 dict(d="2b",k="short",m=1,q="What is a habitat?",a="The place where a plant or animal lives and finds everything it needs.",g="Accept: where an animal or plant lives / gets what it needs."),
 dict(d="2a",k="mc",m=1,q="In paragraph 2, what does the word “glide” mean?",opts=["Jump high","Move smoothly","Sink slowly","Swim fast"],a="B"),
 dict(d="2b",k="find",m=1,q="Find and copy the word from paragraph 3 that describes the eggs that frogs lay.",a="jelly-like",g="Accept “jelly-like” only."),
 dict(d="2b",k="short",m=1,q="Why do pond skaters not sink?",a="Their bodies are light and their long thin legs spread their weight.",g="Accept either idea: light bodies or thin legs spreading their weight."),
 dict(d="2c",k="order",m=1,q="Number the events from 1 to 4 to show how a dragonfly nymph changes into an adult dragonfly.",items=["The dragonfly flies away.","The nymph hides in the mud.","The nymph’s skin splits open.","The nymph climbs up a plant stem."],a=[4,1,3,2],g=Q2),
 dict(d="2b",k="mc",m=1,q="Where do dragonfly nymphs live?",opts=["On the surface of the pond","In the mud at the bottom","In the leaves of water lilies","At the edge of the pond"],a="B"),
 dict(d="2d",k="short",m=1,q="Why might tadpoles need to be careful near the bottom of the pond?",a="Dragonfly nymphs hide in the mud and snap them up.",g="Accept any answer that says nymphs eat / catch tadpoles."),
 dict(d="2d",k="short",m=1,q="Give one reason why plants are important in a pond.",a="They give shade / hiding places, or they make oxygen for animals to breathe.",g="Accept any one reason from paragraph 5."),
 dict(d="2d",k="short",m=1,q="Why do you think a heron stands very still at the edge of the pond?",a="So that the fish do not notice it and it can catch one.",g="Accept: so it does not scare the fish / so it can catch food."),
 dict(d="2b",k="tf",m=1,q="Tick True or False for each sentence.",items=["Frogs lay their eggs in autumn.","Tadpoles feed on tiny green plants.","Herons live under the water.","Water lilies have leaves that float."],a=["F","T","F","T"],g=TF),
 dict(d="2c",k="mc",m=1,q="Which is the best heading for paragraph 4?",opts=["How to dig a pond","Birds at the pond","Life at the bottom of the pond","Plants that float"],a="C"),
 dict(d="2d",k="short",m=1,q="The text says a pond is “a busy habitat” even though it can look quiet. Why is this?",a="Because hundreds of small creatures live in it (that you cannot see from the bank).",g="Accept any answer about lots of animals living in a pond."),
])

T(22, "22-3", "The Missing Biscuits", "Narrative", [
"On Monday, there were ten shortbread biscuits in Nani’s old blue tin. On Tuesday, there were eight. By Wednesday, there were only five, and Nani was puzzled.",
"Ravi and his cousin Ellie were staying for the week. Ellie looked at Ravi. “You had two extra yesterday,” she said. “I saw you.”",
"“I did not!” said Ravi, going red. “I only ate the one you gave me.”",
"They glared at each other until Nani held up her hand. “Nobody is in trouble,” she said. “But I would like to know who it is.”",
"Ravi decided to be a detective. He fetched his notebook and searched the kitchen. On the windowsill beside the tin, he found a scatter of crumbs. There were tiny scratches on the lid, and one corner of it looked nibbled. Outside the window, on the sill, there were small muddy prints with thin, pointed toes.",
"“Ellie, come and look at this!” he called. “Whoever took the biscuits did not use the door. They came in through the window.”",
"“Then it must be a burglar,” whispered Ellie.",
"Ravi shook his head. “A burglar would take the whole tin. And no burglar has feet as small as these.”",
"The next afternoon, the cousins hid behind the curtain, with the window open a crack. They waited for a long time. Just as Ellie’s legs began to ache, a bushy grey tail appeared. A squirrel leapt onto the sill, sniffed the air and lifted the lid with its paws. It grabbed a biscuit, stuffed it into its cheek and scampered away.",
"“It’s a squirrel!” hissed Ravi. Ellie giggled so much that the curtain shook.",
"They told Nani everything. She laughed until she had to wipe her eyes. “Well, that is a relief,” she said. “I thought I had forgotten how to count!”",
"From then on, the tin stayed shut on a high shelf, and a small pile of nuts waited on the windowsill instead. Ellie said sorry to Ravi, and he shared his last biscuit with her.",
], [
 dict(d="2b",k="short",m=1,q="How many biscuits were left in the tin on Wednesday?",a="Five.",g="Accept five or 5."),
 dict(d="2a",k="find",m=1,q="Find and copy one word that tells you how Nani felt about the biscuits.",a="puzzled",g="Accept “puzzled” only."),
 dict(d="2d",k="short",m=1,q="Why did Ellie think that Ravi had taken the biscuits?",a="She had seen him eat two extra biscuits.",g="Accept any answer that mentions Ravi having extra biscuits."),
 dict(d="2b",k="mc",m=1,q="What did Ravi find on the windowsill beside the tin?",opts=["A note from Nani","Some crumbs and scratches","A broken plate","A trail of sugar"],a="B"),
 dict(d="2d",k="short",m=1,q="What clue showed Ravi that the thief came through the window and not the door?",a="The crumbs and muddy prints were on the windowsill (and the window was open).",g="Accept any answer that mentions the prints or crumbs on the windowsill."),
 dict(d="2d",k="short",m=1,q="Ravi said it was not a burglar. Give one reason he gave.",a="A burglar would take the whole tin / a burglar’s feet would not be so small.",g="Accept either reason."),
 dict(d="2a",k="mc",m=1,q="In the story, what does the word “scampered” mean?",opts=["Sat down","Fell over","Ate greedily","Ran quickly with small steps"],a="D"),
 dict(d="2c",k="order",m=1,q="Number the events from 1 to 4 to show the order they happened in the story.",items=["Nani laughed until she wiped her eyes.","Ravi found crumbs on the windowsill.","Nani found only five biscuits in the tin.","The cousins hid behind the curtain."],a=[4,2,1,3],g=Q2),
 dict(d="2b",k="tf",m=1,q="Tick True or False for each sentence.",items=["Ravi and Ellie were brother and sister.","The squirrel lifted the lid with its paws.","The squirrel was black.","Nani left nuts on the windowsill."],a=["F","T","F","T"],g=TF),
 dict(d="2d",k="short",m=1,q="Why do you think Ellie said sorry to Ravi at the end?",a="Because she had blamed him for taking the biscuits and he had not done it.",g="Accept any answer that shows she knew she had blamed him wrongly."),
 dict(d="2e",k="short",m=1,q="What do you think the squirrel will do when it finds the nuts on the windowsill?",a="It will eat them / take them away.",g="Accept any sensible prediction, such as eating the nuts or coming back for more."),
 dict(d="2c",k="mc",m=1,q="Which sentence best sums up the story?",opts=["Two cousins argue and then discover who had really taken the biscuits.","Nani forgets how to count.","Ravi loses his notebook in the kitchen.","A burglar breaks into Nani’s house."],a="A"),
])

T(22, "22-4", "How a Zip Works", "Explanation", [
"Look closely at the zip on a coat or a school bag, and you will see two long rows of tiny teeth. When the zip is closed, the teeth on one side lock into the teeth on the other, holding the two edges of cloth tightly together. Yet all it takes to open or close a zip is one small pull. How does it work?",
"The secret is a small part called the slider. The slider is the piece you hold when you pull the zip up or down. Inside it, there is a Y-shaped channel, like a tiny tunnel that splits into two at one end.",
"Each tooth in the zip has a bump on one side and a hollow on the other. When two teeth are pressed together, the bump on one tooth fits into the hollow on its partner, like two pieces of a puzzle. This is called interlocking.",
"When you pull the slider up, the two rows of teeth enter the wide end of the Y separately. As they travel along the tunnel, the walls squeeze the rows closer and closer together. By the time the teeth leave the narrow end, the bumps and hollows have met and clicked into place. The zip is closed.",
"Pulling the slider down does the opposite. Inside the slider, there is a small wedge that pushes between the teeth and forces them apart. The two rows come out through the wide end of the Y separately, and the zip is open again.",
"Every zip also has a stop at the top and another at the bottom. These small pieces of metal or plastic make sure that the slider cannot slip off the end of the rows.",
"Zips were first made more than a hundred years ago. They soon became popular because they were much quicker to fasten than a long line of buttons or laces. Today, you can find them on coats, bags, tents, sleeping bags and even on the cushions on your sofa.",
], [
 dict(d="2b",k="short",m=1,q="What is the name of the part that you hold to pull a zip up or down?",a="The slider.",g="Accept slider."),
 dict(d="2b",k="find",m=1,q="Find and copy the words from paragraph 2 that describe the shape of the tunnel inside the slider.",a="Y-shaped channel",g="Accept “Y-shaped channel”. Also accept “Y-shaped”."),
 dict(d="2a",k="mc",m=1,q="In paragraph 3, what does the word “interlocking” mean?",opts=["Breaking apart","Fitting together","Getting stuck","Moving quickly"],a="B"),
 dict(d="2c",k="order",m=1,q="Number the steps from 1 to 4 to show how a zip is closed.",items=["The walls of the tunnel squeeze the teeth together.","The bumps click into the hollows.","The teeth enter the wide end of the Y.","You pull the slider up."],a=[4,1,2,3],g=Q2),
 dict(d="2d",k="short",m=1,q="Why does the zip stay closed after the slider has moved past the teeth?",a="The bumps and hollows have clicked together, so the teeth are interlocked.",g="Accept any answer about the teeth being locked or fitted together."),
 dict(d="2b",k="tf",m=1,q="Tick True or False for each sentence.",items=["A zip has two rows of teeth.","Each tooth has a bump on one side and a hollow on the other.","The wedge helps to close the zip.","A zip has a stop at the top and at the bottom."],a=["T","T","F","T"],g=TF),
 dict(d="2d",k="short",m=1,q="What is the job of the wedge inside the slider?",a="It pushes between the teeth and forces them apart when the zip is opened.",g="Accept any answer about separating the teeth or opening the zip."),
 dict(d="2d",k="short",m=1,q="What might happen if a zip had no stop at the top?",a="The slider could slip off the end.",g="Accept any answer that says the slider (or the pull) would come off."),
 dict(d="2b",k="mc",m=1,q="Which sentence describes a tooth correctly?",opts=["It has two bumps.","It has a hollow on both sides.","It is made only of metal.","It has a bump on one side and a hollow on the other."],a="D"),
 dict(d="2d",k="short",m=1,q="Why did zips become more popular than buttons and laces?",a="They were quicker to fasten.",g="Accept: quicker / faster / easier. Do not accept “they are newer”."),
 dict(d="2g",k="short",m=1,q="In paragraph 3, the author says the teeth fit together “like two pieces of a puzzle”. Why does the author use this comparison?",a="To help the reader picture how the bump and hollow fit exactly together.",g="Accept any answer about helping the reader understand how the teeth fit."),
 dict(d="2c",k="mc",m=1,q="Which is the best heading for paragraph 5?",opts=["How a zip opens","Where zips are used","Why zips are popular","Making a zip"],a="A"),
])

T(22, "22-5", "Sports Day", "Recount (Fictional)", [
"Yesterday was Sports Day, the day I had been looking forward to and worrying about for weeks. The sun was shining, the field smelt of freshly cut grass, and every child wore the colour of their team. I was in Team Green.",
"My first race was the sack race. I hopped as fast as I could, but halfway down the track my legs tangled and I toppled onto the grass. My team groaned, and I felt my cheeks burn. Then my friend Ben ran over from the side and held out his hand. “Up you get!” he said. “You are nearly there.” I finished in fourth place, and I did not mind at all.",
"After lunch came the egg-and-spoon race, which was the one I was most nervous about. I walked as carefully as I could, holding my breath and keeping my eyes fixed on the wobbling egg. Beside me, Ben was doing the same. Suddenly, his egg slipped off the spoon and bounced away across the grass.",
"I could have run on. I was in second place, and the finish line was close. Instead, I stopped and helped him to catch it. Ben put the egg back on his spoon, and we walked the last few steps side by side. We came last, but nobody in Team Green laughed. They cheered louder than they had cheered all day.",
"The last event was the team relay. Team Yellow ran brilliantly, and their final runner crossed the line with her arms in the air. At the end of the afternoon, Mr Evans, the headteacher, stood up to give out the prizes. The trophy for the most points went to Team Yellow, and they whooped and clapped.",
"Then Mr Evans smiled. “There is one more cup,” he said. “It is for the team that showed the best sportsmanship. Today, I watched children help each other up, encourage each other and cheer for others, and I am delighted to give this cup to Team Green.”",
"I felt as if my chest might burst with pride. It was not a race that I won, but it was the best Sports Day I have ever had.",
], [
 dict(d="2b",k="short",m=1,q="Which team was the writer in?",a="Team Green.",g="Accept Team Green / Green."),
 dict(d="2b",k="find",m=1,q="Find and copy the words that tell you what the field smelt like.",a="freshly cut grass",g="Accept “freshly cut grass” only."),
 dict(d="2c",k="order",m=1,q="Number the events from 1 to 4 to show the order they happened in the story.",items=["Mr Evans gave Team Green a cup.","The writer fell over in the sack race.","Ben’s egg fell off his spoon.","The writer ate lunch."],a=[4,1,3,2],g=Q2),
 dict(d="2d",k="short",m=1,q="How can you tell that the writer felt embarrassed when she fell over?",a="Her cheeks burned.",g="Accept: her cheeks felt hot / she felt her cheeks burn."),
 dict(d="2a",k="mc",m=1,q="In paragraph 3, what does the word “nervous” mean?",opts=["Worried","Sleepy","Hungry","Angry"],a="A"),
 dict(d="2d",k="short",m=1,q="Why do you think the writer stopped to help Ben when she could have run on?",a="She is kind / she wanted to be a good friend.",g="Accept any answer that shows kindness, friendship or fair play."),
 dict(d="2b",k="tf",m=1,q="Tick True or False for each sentence.",items=["The writer finished the sack race in fourth place.","The writer won the egg-and-spoon race.","Team Yellow won the trophy for most points.","Mr Evans is the headteacher."],a=["T","F","T","T"],g=TF),
 dict(d="2d",k="short",m=1,q="Why did nobody in Team Green laugh when the writer and Ben came last?",a="They were proud of how the two had helped each other.",g="Accept any answer that shows they admired the kindness or teamwork."),
 dict(d="2b",k="mc",m=1,q="What did Team Green win?",opts=["The trophy for the most points","A cup for sportsmanship","The sack race","The relay race"],a="B"),
 dict(d="2g",k="short",m=1,q="The writer says she felt as if her chest “might burst with pride”. What does this tell you about how she felt?",a="She felt extremely proud.",g="Accept: very proud / happy / full of pride."),
 dict(d="2c",k="mc",m=1,q="Which sentence best sums up the story?",opts=["A girl wins every race at Sports Day.","Being kind mattered more than winning at Sports Day.","Team Yellow is the best team.","Ben was too slow to finish."],a="B"),
 dict(d="2e",k="short",m=1,q="What do you think the writer will do at next year’s Sports Day?",a="Help others and try her best.",g="Accept any sensible prediction linked to the text, such as being kind again or trying hard."),
])

T(22, "22-6", "How to Explore a Rock Pool", "Procedural", [
"A rock pool is a small pool of sea water left behind among the rocks on the seashore. It is a wonderful place to find sea creatures, and you do not need any special equipment to look for them. Follow these steps to explore a rock pool safely and to look after the animals that live there.",
"You will need: a bucket, a small net, a pair of shoes with a good grip, and an adult to come with you.",
"First, always go with an adult. Ask them to check that the rocks are safe to walk on, and stay where they can see you. Wet rocks and seaweed are slippery, so walk slowly and never run.",
"Next, fill your bucket with sea water from the pool. This will be a temporary home for any animals you decide to look at more closely.",
"Then sit quietly beside the pool and watch. Many creatures hide when they feel movement, so give them a few minutes to come out. Look for crabs scuttling sideways, small fish darting between the weeds, and limpets, which are shellfish that stick tightly to the rocks.",
"After that, look carefully under the seaweed and around the edges of stones. Lift them gently with one hand, and put them back exactly as you found them. Anemones may look like blobs of red or green jelly when they are out of the water, but underwater they open up into a ring of soft, waving tentacles.",
"If you spot a small animal you would like to see up close, use the net gently to scoop it into the bucket. Never pull a limpet off a rock, and never pick up a crab by its legs. Look for a minute or two, and then tip the animal back into the pool where you found it.",
"Finally, when you have finished exploring, take away everything that you brought with you, and wash your hands when you get home.",
"Remember that rock pools are homes, not playgrounds. If you are careful and quiet, you may discover something amazing.",
], [
 dict(d="2b",k="short",m=1,q="What is a rock pool?",a="A small pool of sea water left among the rocks on the seashore.",g="Accept: a pool of sea water among rocks."),
 dict(d="2b",k="short",m=1,q="Who should you always go with when you explore a rock pool?",a="An adult.",g="Accept adult / grown-up."),
 dict(d="2a",k="mc",m=1,q="In paragraph 4, what does the word “temporary” mean?",opts=["Lasting only for a short time","Very large","Dangerous","Lasting for ever"],a="A"),
 dict(d="2c",k="order",m=1,q="Number the steps from 1 to 4 to show the order in which you should do them.",items=["Use the net to scoop up an animal.","Fill the bucket with sea water.","Sit quietly beside the pool and watch.","Ask an adult to check that the rocks are safe."],a=[4,2,3,1],g=Q2),
 dict(d="2d",k="short",m=1,q="Why should you walk slowly and never run near a rock pool?",a="Wet rocks and seaweed are slippery.",g="Accept any answer about slipping or falling."),
 dict(d="2d",k="short",m=1,q="Why does the text tell you to sit quietly and watch for a few minutes?",a="Many creatures hide when they feel movement, so you give them time to come out.",g="Accept any answer that says animals hide if you move or make a noise."),
 dict(d="2b",k="find",m=1,q="Find and copy the word from paragraph 5 that tells you how crabs move.",a="sideways",g="Accept “sideways” only."),
 dict(d="2b",k="tf",m=1,q="Tick True or False for each sentence.",items=["You need special equipment to explore a rock pool.","Limpets stick tightly to rocks.","You should put stones back where you found them.","You should pick crabs up by their legs."],a=["F","T","T","F"],g=TF),
 dict(d="2d",k="short",m=1,q="Why must you tip the animal back into the pool where you found it?",a="It lives there / the pool is its home.",g="Accept any answer that says the pool is the animal’s home."),
 dict(d="2d",k="short",m=1,q="The text says, “rock pools are homes, not playgrounds”. What does this mean?",a="You should take care of the animals and not treat the pool as a place to play roughly.",g="Accept any answer about respecting the animals’ home."),
 dict(d="2b",k="mc",m=1,q="What might an anemone look like when it is out of the water?",opts=["A ring of soft tentacles","A hard shell","A blob of jelly","A small fish"],a="C"),
 dict(d="2c",k="mc",m=1,q="Which is the best heading for paragraph 7?",opts=["Catching an animal and putting it back","Finding crabs on the beach","Walking on wet rocks","What to pack in your bag"],a="A"),
])

# ---------------------------------------------------------------- LEVEL 23
T(23, "23-1", "The Piano Tuner", "Narrative", [
"Kofi had expected his aunt’s job to be dull. When Aunt Efua announced that she would spend Saturday tuning the grand piano in the town hall, he pictured a room full of clanking tools, like a garage. Still, he had nothing else to do, so he tagged along.",
"The hall was cool and echoing. On the stage stood a piano, its black surface polished like a mirror. Aunt Efua lifted the great lid, and Kofi gasped. Inside was a maze of shining strings, more than two hundred of them, stretched tightly across a metal frame.",
"“Every string makes a note,” she explained. “The tighter the string, the higher the note. But strings slowly loosen, and then the notes drift out of tune.” She slotted a metal lever onto one of the pegs at the end of a string and turned it by the smallest amount. “You do not tune a piano with your eyes,” she added. “You tune it with your ears.”",
"She pressed one key again and again. Kofi frowned. At first, all he heard was a single note, but then he noticed a faint wobble in it, like a wah-wah-wah. “Two strings that ought to sound identical,” said Aunt Efua. “When they disagree, you hear that pulsing. My job is to make it slow down until it disappears.”",
"To Kofi’s surprise, she let him help. He pressed the key while she turned the peg, and he called out the moment the wobble melted away. “Stop!” he shouted. “There! It has gone.” Aunt Efua grinned. “You have got good ears, Kofi.”",
"By lunchtime, his neck ached and his ears were tingling, yet he could hear differences he had never noticed before. When at last Aunt Efua played a tune to test the piano, the notes rang out through the hall, clear and rich. Kofi felt a surge of pride, as if he had helped to build it.",
"On the way home, he asked whether it bothered her that nobody ever saw what she did. Aunt Efua laughed. “That is the best part,” she said. “If I do my job properly, nobody notices me at all. They only notice the music.”",
"Kofi looked out of the window and thought about that. Perhaps a job did not have to be noisy to be important. Perhaps the quietest work was sometimes the hardest to see.",
], [
 dict(d="2b",k="mc",m=1,q="Where was the piano that Aunt Efua tuned?",opts=["In a school","In the town hall","In Kofi’s house","In a music shop"],a="B"),
 dict(d="2a",k="mc",m=1,q="In paragraph 1, what does the word “dull” mean?",opts=["Boring","Dangerous","Difficult","Noisy"],a="A"),
 dict(d="2b",k="short",m=1,q="According to Aunt Efua, what happens to the notes when the strings slowly loosen?",a="The notes drift out of tune.",g="Accept: they go out of tune / they sound wrong."),
 dict(d="2d",k="short",m=1,q="Kofi “tagged along” to the town hall. What does this tell you about why he went?",a="He had nothing else to do / he was not very keen or excited to go.",g="Accept any answer showing he went only because he had nothing better to do."),
 dict(d="2c",k="order",m=1,q="Number the events from 1 to 4 to show the order they happened in the story.",items=["Kofi called “Stop!” when the wobble had gone.","Aunt Efua played a tune to test the piano.","Aunt Efua lifted the lid of the piano.","Aunt Efua explained that tighter strings make higher notes."],a=[3,4,1,2],g=Q2),
 dict(d="2d",k="short",m=1,q="Aunt Efua says, “You tune it with your ears.” What does she mean?",a="Tuning depends on listening carefully to the sounds, not looking at the piano.",g="Accept any answer about listening to the notes."),
 dict(d="2g",k="short",m=1,q="The writer describes the piano’s surface as “polished like a mirror”. What does this tell you about the piano?",a="It was very shiny and clean.",g="Accept shiny / gleaming / spotless."),
 dict(d="2d",k="short",m=1,q="How do you know that Kofi’s opinion of his aunt’s job changed during the day? Give one piece of evidence from the text.",a="He felt a surge of pride / he could hear differences / he thought about how important quiet work can be.",g="Accept any one relevant piece of evidence from paragraphs 5 to 8."),
 dict(d="2b",k="tf",m=1,q="Tick True or False for each sentence.",items=["The piano has more than two hundred strings.","Aunt Efua used a lever to turn the pegs.","Kofi was not allowed to help.","A faint wobble means two strings are not matching."],a=["T","T","F","T"],g=TF),
 dict(d="2d",k="short",m=1,q="Why did Kofi feel “a surge of pride” when the notes rang out?",a="He had helped to make the piano sound good.",g="Accept any answer about his having helped with the tuning."),
 dict(d="2c",k="mc",m=1,q="What is the main message of the last two paragraphs?",opts=["Quiet jobs can be important even if people do not notice them.","Pianos are too difficult to tune.","Kofi should learn to play the piano.","Noisy jobs are the best."],a="A"),
 dict(d="2e",k="short",m=1,q="What do you think Kofi might ask Aunt Efua the next time he sees her? Give a reason.",a="He may ask to help her again, because he enjoyed the tuning and was good at hearing the wobble.",g="Accept any sensible prediction supported by the text."),
])

T(23, "23-2", "How a Canal Lock Works", "Explanation", [
"A canal is a waterway dug by people, and its water lies almost flat. The land it crosses, however, is not flat at all. Hills and valleys mean that the ground rises and falls, and a boat cannot simply sail uphill. To solve this problem, canal builders invented the lock, a clever device that lifts boats up and lowers them down.",
"A lock is a long, narrow chamber with a heavy gate at each end. On one side of the lock, the canal is higher, and on the other side, it is lower. Each gate has a small opening in it called a paddle, which can be opened and closed to let water flow through. No pumps are needed. The water moves by itself, because water always flows from a higher level to a lower level.",
"Imagine that a boat is heading uphill. First, the boat enters the lock through the lower gate, which is open. The lock is full only up to the lower level. Next, the lock keeper closes the lower gate behind the boat and opens the paddles in the upper gate. Water from the higher canal begins to rush into the chamber, and the boat slowly rises with the water.",
"Eventually, the water inside the lock reaches the same height as the canal ahead. Water stops flowing once both sides are level. Only now can the upper gate be pushed open, because before that, the weight of the water on the other side held it firmly shut. The boat can then sail out and continue on its way at the higher level.",
"When a boat is heading downhill, everything happens in reverse. The boat enters the full lock through the upper gate, and the gate is closed behind it. Then the paddles in the lower gate are opened, and water drains out of the chamber into the lower canal. The boat sinks lower and lower until it is level with the water on the far side, and then the lower gate can be opened.",
"Many of Britain’s canals were built more than two hundred years ago, and some are still used today, mainly by narrowboats. A steep hill may need a whole staircase of locks, one after another, so that a boat can climb a great height in easy steps. The idea is simple, but it lets boats travel across hills without any engine doing the lifting.",
], [
 dict(d="2b",k="mc",m=1,q="Why did canal builders invent the lock?",opts=["To stop boats from sinking","So that boats could travel across land that rises and falls","To make canals deeper","To keep the water clean"],a="B"),
 dict(d="2a",k="mc",m=1,q="In paragraph 2, what does the word “chamber” mean?",opts=["A small boat","A gate","An enclosed space","A pipe"],a="C"),
 dict(d="2b",k="short",m=1,q="What is a paddle?",a="A small opening in a gate that can be opened to let water flow through.",g="Accept any answer that mentions an opening in the gate for water."),
 dict(d="2c",k="order",m=1,q="Number the steps from 1 to 4 to show how a boat goes uphill through a lock.",items=["The upper gate is opened.","The boat enters through the lower gate.","Water flows in and the boat rises.","The lower gate is closed."],a=[4,1,3,2],g=Q2),
 dict(d="2d",k="short",m=1,q="Why do locks not need pumps?",a="Because water flows by itself from a higher level to a lower level.",g="Accept any answer about water flowing downhill on its own."),
 dict(d="2d",k="short",m=1,q="Why can the upper gate not be opened until the water in the lock is level?",a="The weight of the water on the other side holds it firmly shut.",g="Accept any answer about the water pressing on the gate."),
 dict(d="2b",k="tf",m=1,q="Tick True or False for each sentence.",items=["A lock has a gate at each end.","A lock keeper opens the paddles in the lower gate to lift a boat.","Boats travelling downhill enter the lock through the upper gate.","All British canals are less than a hundred years old."],a=["T","F","T","F"],g=TF),
 dict(d="2d",k="short",m=1,q="A boat is going downhill. What happens to the water in the lock after the lower paddles are opened?",a="It drains out into the lower canal.",g="Accept: it flows out / it goes down."),
 dict(d="2c",k="mc",m=1,q="Which sentence best sums up paragraph 4?",opts=["The boat has to sail faster.","Water stops flowing when both sides are level, so the gate can then be opened.","Canals are always flat.","The lock keeper goes home."],a="B"),
 dict(d="2d",k="short",m=1,q="Why might a steep hill need a staircase of locks?",a="Each lock raises the boat only a little, so several are needed to climb a great height.",g="Accept any answer about climbing in easy steps or several small lifts."),
 dict(d="2g",k="short",m=1,q="The author calls the lock “a clever device”. Why do you think the author chose the word “clever”?",a="Because the lock solves a difficult problem in a simple way.",g="Accept any answer that shows the idea is smart, well thought out or effective."),
 dict(d="2d",k="short",m=1,q="What does the last sentence suggest about how locks lift boats?",a="No engine is needed / the water does the lifting.",g="Accept any answer that mentions the water doing the work."),
])

T(23, "23-3", "The Glasshouse", "Description", [
"Outside, the rain hammered on the roof, but inside the glasshouse it was quiet and warm. Grandpa Joe pushed open the door for me and a wave of damp air rolled out to meet us, thick and sweet and smelling of soil. I stepped in, and the door clicked shut behind me, leaving the grey winter afternoon on the other side of the glass.",
"Every pane was fogged with tiny beads of water, so the whole world outside had melted into a soft, blurry green. Drops gathered on the glass, swelled and then slid down in shining trails. Above my head, a tangle of vines climbed the metal frame, their curling tendrils reaching out like small, searching fingers.",
"Along the benches sat rows of clay pots, each one crowded with plants. There were tomatoes, hanging in heavy red clusters, and pale green lettuces frilled like ballgowns. At the far end, a single orchid stood in a blue pot, its petals a deep purple, as if it had been dipped in ink. Grandpa Joe said that it had taken him three years to persuade it to flower.",
"I walked slowly along the narrow path, and the gravel crunched beneath my boots. A watering can dripped steadily in one corner, and each drop landed with a tiny plink. Somewhere near the roof, a bumblebee was buzzing lazily from flower to flower. It seemed to think that it was summer.",
"It was so warm that I unzipped my coat. The air felt heavy, almost like a blanket, and my glasses misted over. Grandpa Joe laughed and handed me a cloth. “That is the price you pay,” he said. “It is worth it, though, isn’t it?”",
"I picked a ripe cherry tomato and dropped it into my palm. It was still warm from the air, and its skin was smooth and shiny. When I bit into it, it burst, sweet and sharp, on my tongue. Beyond the glass, the rain drummed on and on, but in there, among the leaves, it felt like a secret place where winter could not reach.",
], [
 dict(d="2b",k="short",m=1,q="What was the weather like outside the glasshouse?",a="It was raining.",g="Accept rain / wet / grey."),
 dict(d="2a",k="mc",m=1,q="In paragraph 2, what does the word “tendrils” mean?",opts=["Thin, curling stems that plants use to climb","Large flat leaves","Drops of water","Metal supports"],a="A"),
 dict(d="2b",k="find",m=1,q="Find and copy the phrase that tells you how long it took Grandpa Joe to persuade the orchid to flower.",a="three years",g="Accept “three years” only."),
 dict(d="2g",k="short",m=1,q="The author writes that the tendrils were “like small, searching fingers”. What does this description help you to imagine?",a="The tendrils reaching out slowly as if feeling for something to hold.",g="Accept any answer about the tendrils looking like fingers reaching or feeling their way."),
 dict(d="2d",k="short",m=1,q="Look at paragraph 4. Why did the bumblebee seem to think it was summer?",a="Because the glasshouse was so warm and full of flowers.",g="Accept any answer about warmth or flowers."),
 dict(d="2d",k="short",m=1,q="Why did the narrator’s glasses mist over?",a="The warm, damp air met the cooler glass.",g="Accept: the air was warm/damp/humid. Accept any answer linked to the warm damp air."),
 dict(d="2c",k="order",m=1,q="Number the events from 1 to 4 to show the order they happened in the description.",items=["The narrator ate a cherry tomato.","The narrator unzipped her coat.","Grandpa Joe opened the door.","The narrator walked along the gravel path."],a=[4,3,1,2],g=Q2),
 dict(d="2b",k="tf",m=1,q="Tick True or False for each sentence.",items=["The orchid was purple.","The lettuces looked like ballgowns.","The glasshouse felt cold.","The tomatoes were hanging in red clusters."],a=["T","T","F","T"],g=TF),
 dict(d="2g",k="mc",m=1,q="The author describes the orchid as “dipped in ink”. What does this suggest about its colour?",opts=["Pale and faint","Rich and dark","Bright yellow","Spotted"],a="B"),
 dict(d="2d",k="short",m=1,q="What does the phrase “a secret place where winter could not reach” tell you about how the narrator felt in the glasshouse?",a="Safe, warm and happy, cut off from the cold weather outside.",g="Accept any answer showing the narrator felt cosy, safe or special."),
 dict(d="2c",k="mc",m=1,q="Which sentence best sums up paragraph 3?",opts=["Grandpa Joe grows many kinds of plants, including an unusual orchid.","The glasshouse has a leaking roof.","The narrator dislikes tomatoes.","Grandpa Joe is going to sell his plants."],a="A"),
 dict(d="2d",k="short",m=1,q="Grandpa Joe says, “It is worth it, though, isn’t it?” What does he think is worth it?",a="Having misty glasses because of the warm air, to enjoy the glasshouse.",g="Accept any answer that means the warm glasshouse is worth the little inconvenience."),
])

T(23, "23-4", "The Sound Makers", "Information Report", [
"When you watch a film, you hear footsteps on a path, a door creaking open, or a horse galloping across a field. You might think that these sounds were recorded while the film was being shot, but most of them were not. Instead, they were added afterwards by a Foley artist, a person with one of the most unusual jobs in the film industry.",
"The job is named after Jack Foley, a sound pioneer who worked in films almost a hundred years ago. A Foley artist works in a special studio, watching the film on a screen and making each sound at exactly the right moment. If a character steps on to gravel, the Foley artist walks on a tray of real gravel in perfect time with the picture.",
"Why are the sounds not simply recorded when the film is made? The main reason is that microphones on a film set are aimed at the actors’ voices. Other noises are often too quiet, too muddled or drowned out by the crew nearby. In addition, some of the things you see on screen make no sound at all, or do not exist in real life, such as a dragon flapping its wings.",
"So Foley artists collect strange objects, and they use them in surprising ways. The clip-clop of a horse can be made by knocking two coconut shell halves together on a hard surface. Crumpling a sheet of cellophane sounds very like a crackling fire. A pair of leather gloves, flapped quickly, makes the sound of a bird’s wings. Even the crunch of footsteps in snow can be created by squeezing a packet of cornflour.",
"To be good at the job, a Foley artist needs sharp ears, great timing and a lot of imagination. They must listen carefully to the sounds around them every day and think, “What could I use to copy that?” Often, the real thing does not sound right on film, and something quite different works far better. A real fire, for instance, may sound flat and quiet, while the cellophane sounds lively.",
"Many of the noises we think of as real are actually cleverly disguised props. The next time you watch a film, listen closely. Somewhere behind the screen, a Foley artist may have been waving a pair of gloves in a quiet studio.",
], [
 dict(d="2b",k="short",m=1,q="What is a Foley artist?",a="A person who adds sounds to a film after it has been shot.",g="Accept: someone who makes sound effects for films."),
 dict(d="2a",k="mc",m=1,q="In paragraph 3, what does the word “muddled” mean?",opts=["Mixed up and unclear","Very loud","Perfectly clear","Far away"],a="A"),
 dict(d="2b",k="find",m=1,q="Find and copy the words that tell you what is used to make the sound of a horse’s hooves.",a="coconut shell halves",g="Accept “coconut shell halves”. Also accept “coconut shell”."),
 dict(d="2b",k="short",m=1,q="What can be used to make the sound of a crackling fire?",a="Crumpled cellophane.",g="Accept cellophane."),
 dict(d="2d",k="short",m=1,q="Why are the sounds in a film not simply recorded on set? Give one reason.",a="The microphones are aimed at the actors; other noises are too quiet, muddled or drowned out; some things (like dragons) make no real sound.",g="Accept any one reason from paragraph 3."),
 dict(d="2c",k="order",m=1,q="Number the steps from 1 to 4 to show how a sound gets into a film.",items=["The Foley artist makes the sound in time with the picture.","The film is shot on set.","The Foley artist watches the film on a screen.","The sound is added to the film."],a=[4,1,3,2],g=Q2),
 dict(d="2b",k="tf",m=1,q="Tick True or False for each sentence.",items=["Foley artists are named after Jack Foley.","A Foley artist uses a tray of gravel to make footsteps.","Foley artists work on the film set while the film is shot.","Cornflour can be squeezed to sound like footsteps in snow."],a=["T","T","F","T"],g=TF),
 dict(d="2d",k="short",m=1,q="Why do you think a Foley artist might prefer cellophane to a real fire?",a="A real fire may sound flat and quiet, but cellophane sounds livelier on film.",g="Accept any answer about the real fire not sounding right on film."),
 dict(d="2d",k="short",m=1,q="The text says that a Foley artist needs “a lot of imagination”. Why?",a="They have to think of everyday objects that can copy other sounds.",g="Accept any answer about finding objects that sound like something else."),
 dict(d="2g",k="mc",m=1,q="In the last paragraph, why does the author call the sounds “cleverly disguised props”?",opts=["They are made with everyday objects that pretend to be something else.","They are hidden in the studio.","They are very loud.","They are recorded by the actors."],a="A"),
 dict(d="2c",k="mc",m=1,q="Which is the best heading for paragraph 4?",opts=["Where to buy coconuts","Everyday objects that make film sounds","Jack Foley’s life","How to make a film"],a="B"),
 dict(d="2e",k="short",m=1,q="A film shows a bird flying past. Using the text, how might a Foley artist make the sound of its wings?",a="By flapping a pair of leather gloves quickly.",g="Accept: leather gloves flapped / waved."),
])

T(23, "23-5", "The Sandcastle Contest", "Narrative", [
"The whole beach seemed to be buzzing. Flags fluttered above a long table, and families were already marking out squares in the sand with sticks and spades. It was the day of the Sandcastle Contest, and twins Idris and Halima had been planning for weeks.",
"“We will build the tallest castle anyone has ever seen,” declared Idris, dragging a bucket to the water’s edge. “With four towers and a moat.”",
"“And a drawbridge,” added Halima. “Made from a lolly stick.”",
"They worked for nearly two hours. Idris packed the wet sand into the bucket and tipped out perfect towers, while Halima carved windows with the edge of a shell and lined the walls with tiny pebbles. The castle rose until it stood almost as high as their knees. The sun beat down on their backs, and their fingers were wrinkled and gritty, but neither of them noticed.",
"At last, Halima stepped back and clapped. “It is perfect,” she breathed.",
"Just then, a golden retriever came bounding down the beach after a ball. With a single great leap, it crashed through the north tower and skidded straight across the middle of the castle, spraying sand in all directions.",
"The dog’s owner ran up, apologising. “I am so sorry!” she gasped. “I will help you rebuild it.” But the judges were already walking along the row, with only ten minutes left.",
"Idris stared at the heap of sand. His eyes stung, and he swallowed hard. Halima was not upset. She was studying the wreckage with her head on one side, as if she were reading a map.",
"“Look,” she said slowly. “It has gone all crumbly and mysterious. What if it is not a new castle any more? What if it is a ruin, thousands of years old?”",
"Idris blinked. Then his face split into a grin. Together, they scooped out a tunnel and stuck the lolly-stick drawbridge in at a slanting angle. They sprinkled seaweed on top of the fallen towers and stuck a shell on the highest pile of sand, like a flag.",
"When the judges reached them, Halima put on her grandest voice. “Welcome to the Lost City of Sandalia,” she said. “It was destroyed long ago by a mighty golden beast.”",
"The judges laughed out loud. That afternoon, a ribbon was pinned to the ruin, and it was not for the tallest castle. It said Most Imaginative.",
], [
 dict(d="2b",k="short",m=1,q="What was the special event on the beach?",a="A sandcastle contest.",g="Accept Sandcastle Contest."),
 dict(d="2a",k="mc",m=1,q="In paragraph 1, what does the word “buzzing” suggest about the beach?",opts=["It was full of insects.","It was silent.","It was full of excitement.","It was empty."],a="C"),
 dict(d="2b",k="find",m=1,q="Find and copy the words that tell you what Halima used to carve the windows.",a="the edge of a shell",g="Accept “the edge of a shell” or “a shell”."),
 dict(d="2d",k="short",m=1,q="How can you tell that the twins had worked very hard on their castle? Give one piece of evidence.",a="They worked for nearly two hours / their fingers were wrinkled and gritty / they did not notice the sun beating down.",g="Accept any one relevant piece of evidence."),
 dict(d="2c",k="order",m=1,q="Number the events from 1 to 4 to show the order they happened in the story.",items=["The judges laughed and gave a ribbon.","A dog crashed through the castle.","The twins built the towers.","Halima suggested that the castle was an ancient ruin."],a=[4,2,1,3],g=Q2),
 dict(d="2d",k="short",m=1,q="How did Idris feel when he saw the wrecked castle? Use evidence from the text to explain.",a="Upset / near to tears, because his eyes stung and he swallowed hard.",g="1 mark for a suitable feeling supported by the evidence (eyes stung / swallowed hard)."),
 dict(d="2d",k="short",m=1,q="Halima was studying the wreckage “as if she were reading a map”. What does this suggest about her?",a="She was thinking carefully and looking for an idea.",g="Accept any answer about concentration, thinking or seeing possibilities."),
 dict(d="2b",k="tf",m=1,q="Tick True or False for each sentence.",items=["The twins planned to make a drawbridge from a lolly stick.","The dog knocked down the whole castle including the moat.","The dog’s owner offered to help rebuild the castle.","The judges gave the twins a prize for the tallest castle."],a=["T","F","T","F"],g=TF),
 dict(d="2g",k="short",m=1,q="The author says the dog “crashed through the north tower and skidded straight across”. What does this choice of words show about the dog?",a="It was moving fast and not paying attention.",g="Accept: it was fast / careless / out of control / clumsy."),
 dict(d="2d",k="short",m=1,q="Why do you think the judges laughed out loud at the end?",a="They enjoyed Halima’s clever story about the lost city.",g="Accept any answer showing the judges were amused or impressed by the twins’ imagination."),
 dict(d="2c",k="mc",m=1,q="What is the main message of the story?",opts=["Dogs should not be allowed on beaches.","Winning is all that matters.","Sandcastles should be built far from the sea.","Clever thinking can turn a disaster into something good."],a="D"),
 dict(d="2e",k="short",m=1,q="What might Idris and Halima do next year? Give a reason from the story.",a="Enter the contest again with a new imaginative idea, because they enjoyed it and won a prize.",g="Accept any sensible prediction supported by the story."),
])

T(23, "23-6", "Mary Anning, Fossil Hunter", "Recount (Historical)", [
"Mary Anning was born in 1799 in Lyme Regis, a small seaside town on the south coast of England. Her family was poor, and her father made furniture. In his spare time, he searched the nearby cliffs and beaches for fossils, which are the remains of animals and plants that lived long ago and have turned to stone. He sold the best ones to visitors to earn extra money.",
"When Mary’s father died, the family had very little money. Mary and her brother Joseph carried on searching for fossils to sell. The cliffs near their home were crumbling, and after heavy storms, new fossils were often left lying on the beach. Mary learned to spot them among the stones. She had to keep a sharp eye out, for the sea could wash them away.",
"When Mary was about twelve, Joseph found a strange skull sticking out of the cliff. It was long and narrow, with a great many sharp teeth. Over the next year, Mary carefully dug out the rest of the skeleton with a small hammer and brush. It took her months, and she had to work in bad weather. Scientists later decided that it belonged to a huge sea reptile called an ichthyosaur, which had lived millions of years before.",
"The find made Mary well known. Even so, it was hard for her to be taken seriously. She was a girl from a poor family, and at that time, most scientists were wealthy men. Many of them bought her fossils and wrote about them, but they did not always mention her name.",
"In 1823, Mary made another great discovery. She unearthed the first complete skeleton of a plesiosaur, another sea reptile, which had a small head and a very long neck. Some experts could not believe that an animal so odd had ever existed, and at first they thought the skeleton must be a fake. However, other scientists examined it closely and agreed that it was real.",
"Mary spent the rest of her working life hunting for fossils and selling them from a little shop in Lyme Regis. Visitors came from far away to see her collection and to learn from her. Today, her discoveries are on display in museums, and she is remembered as one of the most important fossil hunters in history.",
], [
 dict(d="2b",k="short",m=1,q="Where was Mary Anning born?",a="Lyme Regis.",g="Accept Lyme Regis / a seaside town on the south coast of England."),
 dict(d="2a",k="mc",m=1,q="In paragraph 1, what are fossils?",opts=["Old coins","The remains of animals or plants that lived long ago and have turned to stone","Tools used to dig","Rocks that glow"],a="B"),
 dict(d="2b",k="short",m=1,q="What did Mary’s father do in his spare time?",a="He searched the cliffs and beaches for fossils to sell.",g="Accept any answer about looking for fossils."),
 dict(d="2d",k="short",m=1,q="Why did Mary and Joseph continue to search for fossils after their father died?",a="The family had very little money, and they could sell the fossils.",g="Accept any answer about earning money."),
 dict(d="2c",k="order",m=1,q="Number the events from 1 to 4 to show the order they happened.",items=["Mary found the first complete plesiosaur skeleton.","Joseph found a strange skull in the cliff.","Mary’s father died.","Mary dug out the rest of the skeleton."],a=[4,2,1,3],g=Q2),
 dict(d="2d",k="short",m=1,q="Why did Mary have to “keep a sharp eye out” when she searched the beach?",a="The sea could wash the fossils away.",g="Accept any answer about the sea taking the fossils."),
 dict(d="2b",k="find",m=1,q="Find and copy the words that describe the skull that Joseph found.",a="long and narrow",g="Accept “long and narrow”."),
 dict(d="2d",k="short",m=1,q="Paragraph 4 says it was hard for Mary to be taken seriously. Give one reason why.",a="She was a girl from a poor family and most scientists were wealthy men / her name was not always mentioned.",g="Accept any one reason from paragraph 4."),
 dict(d="2b",k="tf",m=1,q="Tick True or False for each sentence.",items=["Mary was born in 1799.","Mary found a plesiosaur skeleton in 1823.","The plesiosaur had a very short neck.","Mary sold fossils from a shop in Lyme Regis."],a=["T","T","F","T"],g=TF),
 dict(d="2d",k="short",m=1,q="Why do you think some experts thought the plesiosaur skeleton was a fake?",a="They could not believe an animal so odd had ever existed.",g="Accept any answer about the animal looking too strange."),
 dict(d="2g",k="mc",m=1,q="In paragraph 3, the author says Mary “carefully dug out the rest of the skeleton”. Why is the word “carefully” important?",opts=["Because it shows the skeleton was fragile and could easily be damaged","Because it shows she was afraid","Because it shows she was bored","Because it shows she worked fast"],a="A"),
 dict(d="2c",k="mc",m=1,q="Which sentence best sums up the whole text?",opts=["Mary Anning’s father built furniture.","Mary Anning became an important fossil hunter even though she came from a poor family.","Ichthyosaurs lived in the sea.","Lyme Regis is on the south coast."],a="B"),
])
